### ISSUE TITLE
 fatal error: opencv2/core.hpp: No such file or directory

### ISSUE THREAD

**Issue by ztdepztdep** [ginkgo-project/ginkgo#1001]
how to find the opencv2  in the ginkgo, I can't find it in the include directory and src directory.

**Comment by upsj** [comment]
If you have it installed properly via package manager or similar, it should be found automatically. How did you install it?
If it is not found during installation, the corresponding tests are disabled. So from what you are describing, it sounds like your OpenCV installation might be incomplete/broken? Can you attach your CMakeCache.txt file please?

**Comment by yhmtsai** [comment]
If it find the opencv in python, ginkgo can't not use it. In this case, you need to remove the corresponding path from your environment when compiling ginkgo.

**Comment by ztdepztdep** [comment]
> If you have it installed properly via package manager or similar, it should be found automatically. How did you install it? If it is not found during installation, the corresponding tests are disabled. So from what you are describing, it sounds like your OpenCV installation might be incomplete/broken? Can you attach your CMakeCache.txt file please?

Thanks, I reinstalled the opencv and it can find the head file now.
