### ISSUE TITLE
Add support for profiler hooks in logger

### ISSUE THREAD

**Issue by upsj** [ginkgo-project/ginkgo#1036]
Tools like [TAU](https://www.cs.uoregon.edu/research/tau/docs/newguide/bk05rn01.html) or [NVIDIA Toolkit Extensions](https://docs.nvidia.com/cuda/profiler-users-guide/index.html#nvtx) allow applications to log custom events/phases in a nested fashion. We could profit from their tooling by providing loggers wrapping this functionality.

**Comment by pratikvn** [comment]
This is definitely a good idea. I think we already had some effort from @tcojean using PAPI with software defined events.

Additionally, there are a few libraries that can abstract this for different backends as well. This would allow us to for example to have a common instrumentation functions in our code and have that work for different backends that the library uses. Just to mention some libraries which might be useful for this:

1. Tau,
2. Score-P
3. Caliper.

Of course, we always have the option of using the profiler API that Nvidia and ROCM (and DPC++ ? ) provide, but that might be more work and maintenance.
