### ISSUE TITLE
Warning Wdelete-non-abstract-non-virtual-dtor

### ISSUE THREAD

**Issue by bp-intact-solutions** [ginkgo-project/ginkgo#1048]
Hello,
I am using ginkgo/1.4.0 through Conan, and when, in c++, on Mac, I include `#include <ginkgo/ginkgo.hpp>`, then I get a warning:

```
/opt/homebrew/opt/llvm/bin/../include/c++/v1/__memory/unique_ptr.h:57:5: error: delete called on non-final 'gko::log::Record' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
    delete __ptr;
```

I tried the following but got the same error:
```
#ifdef _WIN32
#pragma warning(push, 0)
#else
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Weverything"
#pragma GCC diagnostic ignored "-Wdelete-non-abstract-non-virtual-dtor"
#endif
#include <ginkgo/ginkgo.hpp>
#ifdef _WIN32
#pragma warning(pop)
#else
#pragma GCC diagnostic pop
#endif
```
Any suggestion?
Note that I would like to continue to treat warnings as errors in my project.
Thank you.
Best regards!

**Comment by upsj** [comment]
Thanks for the report! We will only be able to fix this with the next release, but this is definitely a defect we need to address.
