### ISSUE TITLE
Compilation error for sample code

### ISSUE THREAD

**Issue by bp-intact-solutions** [ginkgo-project/ginkgo#1049]
Hello,
I am trying to use ginkgo for solving a linear system but get the following compilation error with the following code (ginkgo_test.txt). I am using a M1 Mac.

I followed https://github.com/fritzgoebel/ginkgo_wiki/wiki/Tutorial-2:-Implement:-Matrices and https://github.com/fritzgoebel/ginkgo_wiki/wiki/Tutorial-3:-Implement:-Solvers.

Did I miss something?

Thank you.

Best regards!

BP

[ginkgo_test.txt](https://github.com/ginkgo-project/ginkgo/files/8837924/ginkgo_test.txt)

```
.conan/data/ginkgo/1.4.0/_/_/package/a6d9ecd51d9301cf890b4d4bfe8a9ed7e68b81f7/include/ginkgo/core/base/abstract_factory.hpp:165:33: error: no matching constructor for initialization of 'gko::EnableDefaultFactory<gko::solver::Cg<>::Factory, gko::solver::Cg<>, gko::solver::Cg<>::parameters_type, gko::LinOpFactory>::components_type' (aka 'std::shared_ptr<const gko::LinOp>')
            this->generate_impl({std::forward<Args>(args)...}).release()));
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ginkgo_test.cpp:51:40: note: in instantiation of function template specialization 'gko::EnableDefaultFactory<gko::solver::Cg<>::Factory, gko::solver::Cg<>, gko::solver::Cg<>::parameters_type, gko::LinOpFactory>::generate<std::unique_ptr<gko::matrix::Dense<>> &>' requested here
  auto ginkgo_solver = solver_factory->generate(mat_A);
```

**Comment by upsj** [comment]
It looks like you are trying to pass an owning unique_ptr to a place that expects a shared_ptr. What you can to is either create the matrix as a shared_ptr from the start (`auto mat_A = gko::share(...)`) or empty the unique_ptr out to create a shared_ptr to be stored in the solver (`generate(gko::share(std::move(mat_A)))`). The latter means that you can't use mat_A to access it anymore, though.

**Comment by upsj** [comment]
@fritzgoebel can you update your examples accordingly?

**Comment by bp-intact-solutions** [comment]
Perfect! Thank you!
[ginkgo_test.txt](https://github.com/ginkgo-project/ginkgo/files/8837971/ginkgo_test.txt)

**Comment by upsj** [comment]
We removed the outdated wiki, so this should be resolved.
