### ISSUE TITLE
Using "modern" CMake in Ginkgo

### ISSUE THREAD

**Issue by gflegar** [ginkgo-project/ginkgo#109]
I always had trouble finding good and up-to-date tutorials about CMake, and how to properly do stuff there (especially the things  that seem to be possible to do in multiple ways).

I think I finally managed to find a good collection of resources [here](https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1).
Just by taking a quick look I already figured out that we're doing some of the things the wrong way which will prevent us in playing nicely with other software.

Someone should go over the materials in the link, and update our build system to follow the rules.

**Comment by upsj** [comment]
A lot of `install_helpers.cmake` is based on [this blog post](https://codingnest.com/basic-cmake-part-2/)
