### ISSUE TITLE
Confusing documentation of stopping criteria

### ISSUE THREAD

**Issue by lahwaacz** [ginkgo-project/ginkgo#1097]
The [gko::stop::mode](https://ginkgo-project.github.io/ginkgo-generated-documentation/doc/develop/group__stop.html#ga5fe97c4263e876f68b5d4a21f0e615b9) enum documents three modes of the residual norm criterion:
<ul>
<li>absolute: Check for tolerance against residual norm. <img class="formulaInl" alt="$ || r || &lt; \tau $" src="https://ginkgo-project.github.io/ginkgo-generated-documentation/doc/develop/form_54.png"></li>
<li>initial_resnorm: Check for tolerance relative to the initial residual norm. <img class="formulaInl" alt="$ \frac{|| r ||}{|| r_0||} &lt; \tau $" src="https://ginkgo-project.github.io/ginkgo-generated-documentation/doc/develop/form_55.png"></li>
<li>rhs_resnorm: Check for tolerance relative to the rhs norm. <img class="formulaInl" alt="$ \frac{|| r ||}{|| b ||} &lt; \tau $" src="https://ginkgo-project.github.io/ginkgo-generated-documentation/doc/develop/form_56.png"> </li>
</ul>

But it is not clear in which criteria it can be applied and how. I guess these two criteria are relevant:

1. The [ResidualNorm](https://ginkgo-project.github.io/ginkgo-generated-documentation/doc/develop/classgko_1_1stop_1_1ResidualNorm.html) class is a stopping criterion which stops the iteration process when the actual residual norm is below a certain threshold relative to.

    the norm of the right-hand side, norm(residual) / norm(right_hand_side) < threshold
    the initial residual, norm(residual) / norm(initial_residual) < threshold.
    one, norm(residual) < threshold.

2. The [ImplicitResidualNorm](https://ginkgo-project.github.io/ginkgo-generated-documentation/doc/develop/classgko_1_1stop_1_1ImplicitResidualNorm.html) class is a stopping criterion which stops the iteration process when the implicit residual norm is below a certain threshold relative to.

    the norm of the right-hand side, implicit_resnorm / norm(right_hand_side) < threshold
    the initial residual, implicit_resnorm / norm(initial_residual) < < threshold.
    one, implicit_resnorm < threshold.

It is also not clear what is the difference between "residual" and "implicit residual".

There are also "specialized" criteria for each mode:

1. The [ResidualNormReduction](https://ginkgo-project.github.io/ginkgo-generated-documentation/doc/develop/classgko_1_1stop_1_1ResidualNormReduction.html) class is a stopping criterion which stops the iteration process when the residual norm is below a certain threshold relative to the norm of the initial residual, i.e.

   when norm(residual) / norm(initial_residual) < threshold.

2. The [RelativeResidualNorm](https://ginkgo-project.github.io/ginkgo-generated-documentation/doc/develop/classgko_1_1stop_1_1RelativeResidualNorm.html) class is a stopping criterion which stops the iteration process when the residual norm is below a certain threshold relative to the norm of the right-hand side, i.e.

   when norm(residual) / norm(right_hand_side) < threshold.

3. The [AbsoluteResidualNorm](https://ginkgo-project.github.io/ginkgo-generated-documentation/doc/develop/classgko_1_1stop_1_1AbsoluteResidualNorm.html) class is a stopping criterion which stops the iteration process when the residual norm is below a certain threshold, i.e.

   when norm(residual) / threshold.

Here the documentation is pretty clear (except why the classes actually exist separately), but the formatting could be improved.

**Comment by lahwaacz** [comment]
Also note that `rhs_resnorm` in the documentation should be `rhs_norm`.

**Comment by MarcelKoch** [comment]
The specialized classes that you mentioned in the last part are actually all deprecated. Instead, only one of the two mentioned above should be used. We will make that clearer in the future.

Regarding the difference between 1&2: 
In the case of 1., the residual vector is used to compute the residual norm, by calling the `compute_norm2` operation on that vector. If the solver does not compute the residual vector (which is actually not the case for any of the currently available solver), then we first compute the residual by computing `b - A*x` in the stopping criteria.
In the case of 2., the criteria does not use the provided residual vector, but uses an approximation of the residual norm provided by the solver (if that is available). For example, in the CG solver, the already computed `rho = r^T * z` is used for that.
In both cases, you can switch between the three different modes `absolute, initial_resnorm, rhs_norm`.
