### ISSUE TITLE
Dead link in INSTALL.md

### ISSUE THREAD

**Issue by lahwaacz** [ginkgo-project/ginkgo#1103]
At the end of [INSTALL.md](https://github.com/ginkgo-project/ginkgo/blob/develop/INSTALL.md), the link to [`test_install`](https://github.com/ginkgo-project/ginkgo/blob/develop/[test_install](https://github.com/ginkgo-project/ginkgo/blob/develop/test_install/CMakeLists.txt)/CMakeLists.txt) does not work.

**Comment by yhmtsai** [comment]
Hi @lahwaacz , thanks for reporting this.
I create the PR #1108, which should fix it after merging.
