### ISSUE TITLE
Deprecation warnings with cuSPARSE 11.8

### ISSUE THREAD

**Issue by lahwaacz** [ginkgo-project/ginkgo#1146]
Building ginkgo with CUDA 11.8 results in many warnings, mostly deprecation warnings from cuSPARSE. I'm attaching a complete build log of the [ginkgo-hpc-git AUR package](https://aur.archlinux.org/packages/ginkgo-hpc-git).

[ginkgo-hpc-git-r5521.8b036c64f4-1-x86_64-build.log](https://github.com/ginkgo-project/ginkgo/files/9792778/ginkgo-hpc-git-r5521.8b036c64f4-1-x86_64-build.log)

**Comment by upsj** [comment]
Thanks for the report! We should add some version compile guards here (mirroring the ones in common_trs_kernels.cuh for csrsm*). Does AUR have a mechanism to compile for specific hardware? SM 3.5 is only being enabled if no GPU is detected at all. You might want to list a set of GPU architectures explicitly (increasing compile time and binary size) or find some other way to make it configurable

**Comment by lahwaacz** [comment]
I'm explicitly setting [-DGINKGO_CUDA_ARCHITECTURES="All"](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ginkgo-hpc-git#n30) because the built package should be usable on any hardware. But the AUR contains just the PKGBUILD, not the binary package itself.

**Comment by upsj** [comment]
In that case, I would suggest listing the non-deprecated SMs instead of `All` to avoid these warnings

**Comment by lahwaacz** [comment]
I could also add the `-Wno-deprecated-gpu-targets` flag to avoid the warnings.

**Comment by upsj** [comment]
That sounds like the best course of action. I'll add the missing compiler guards to deal with the deprecated functionality.
