### ISSUE TITLE
error:  select_classical_spmv: unable to find an eligible kernel

### ISSUE THREAD

**Issue by ztdepztdep** [ginkgo-project/ginkgo#1150]
I have compile the ginkgo lib sucessfully with cuda11.8 support. but when i run an example file. 
it gives me the following error. 

./main 
MapSMtoCores for SM 8.6is undefined. The default value of 64 Cores/SM is used.
terminate called after throwing an instance of 'gko::KernelNotFound'
  what():  /home/ztdep/Downloads/ginkgo/cuda/matrix/csr_kernels.cu:259: select_classical_spmv: unable to find an eligible kernel
Aborted (core dumped)

**Comment by yhmtsai** [comment]
@ztdepztdep thanks for reporting this issue!
The message about SM 8.6 does not lead the following `KernelNotFound` issue.
What's the commit SHA of your current ginkgo?
Could you also add `std::cerr << max_length_per_row << std::endl` before `host_kernel::select_classical_spmv(` at line 467 and line 526 of `ginkgo/cuda/matrix/csr_kernels.cu` and run the example again?

**Comment by ztdepztdep** [comment]
I download the ginkgo from the github. which version should i use?

**Comment by upsj** [comment]
It seems like you are using an outdated version of Ginkgo - the error should appear on line 270, not 259. Can you try the latest state from `develop` and let us know if the issue is still present?

**Comment by ztdepztdep** [comment]
It is working now.. thank you very much for your help.
