### ISSUE TITLE
About building the code with the flag -DGINKGO_BENCHMARK_ENABLE_TUNING=ON

### ISSUE THREAD

**Issue by xwentian2020** [ginkgo-project/ginkgo#1151]
Hi,

The flag -DGINKGO_BENCHMARK_ENABLE_TUNING=ON was added into the cmake command and thereafter in building the source code, some error data were promoted, as shown below.

>  [ 68%] Building CXX object benchmark/tools/CMakeFiles/mtx_to_binary.dir/mtx_to_binary.cpp.o
> [ 68%] Linking CXX executable mtx_to_binary
> /usr/bin/ld: ../../lib/libginkgo_cuda.so.1.5.0: undefined reference to `gko::_tuned_value'
> /usr/bin/ld: ../../lib/libginkgo_cuda.so.1.5.0: undefined reference to `gko::_tuning_flag'
> collect2: error: ld returned 1 exit status
> make[2]: *** [benchmark/tools/CMakeFiles/mtx_to_binary.dir/build.make:104: benchmark/tools/mtx_to_binary] Error 1
> make[1]: *** [CMakeFiles/Makefile2:2316: benchmark/tools/CMakeFiles/mtx_to_binary.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 68%] Linking CXX executable matrix
> [ 68%] Linking CXX executable matrix_complex
> /usr/bin/ld: ../../lib/libginkgo_cuda.so.1.5.0: undefined reference to `gko::_tuned_value'
> /usr/bin/ld: ../../lib/libginkgo_cuda.so.1.5.0: undefined reference to `gko::_tuning_flag'
> collect2: error: ld returned 1 exit status
> make[2]: *** [benchmark/tools/CMakeFiles/matrix.dir/build.make:104: benchmark/tools/matrix] Error 1
> make[1]: *** [CMakeFiles/Makefile2:2252: benchmark/tools/CMakeFiles/matrix.dir/all] Error 2
> /usr/bin/ld: ../../lib/libginkgo_cuda.so.1.5.0: undefined reference to `gko::_tuned_value'
> /usr/bin/ld: ../../lib/libginkgo_cuda.so.1.5.0: undefined reference to `gko::_tuning_flag'
> collect2: error: ld returned 1 exit status
> make[2]: *** [benchmark/tools/CMakeFiles/matrix_complex.dir/build.make:104: benchmark/tools/matrix_complex] Error 1
> make[1]: *** [CMakeFiles/Makefile2:2284: benchmark/tools/CMakeFiles/matrix_complex.dir/all] Error 2

**Comment by xwentian2020** [comment]
Thanks for your quick response to my question. Now I am trying to find out the peak performance of different GPUs in SpMV and notice the code snippet started with **#ifdef GINKGO_BENCHMARK_ENABLE_TUNING** in the spmv.cpp file. I wonder the results made by this code snippet are useful to figure out the maximum GFLOPS value could be get by a target GPU. Since you put this code snippet there, I want to make a try and use this code snippet to compare the performance of the GPUs. Could you tell me how I can make this work done by myself.

**Comment by upsj** [comment]
The flag should not matter to you. To compute the peak performance of the SpMV kernels, you can use the following heuristic:
GFLOP/s = ((number of rows + number of columns) * sizeof(double) + storage size of the matrix as output by the benchmark) / runtime.
Except for the ELL matrix format (where we short-circuit, i.e. a part of the matrix will not be read from memory), this should be a fairly precise result.

**Comment by upsj** [comment]
The flag is only intended for developer usage, so we will not change its behavior. Closing this
