### ISSUE TITLE
`-munsafe-fp-atomics` argument unused warning for HIP

### ISSUE THREAD

**Issue by yhmtsai** [ginkgo-project/ginkgo#1186]
In #1091, we adds the unsafe-fp-atomic into our compilation.
Although HIP should support it after 5, but its shipped clang might not support it yet and throw the unused warning.

We could handle it like https://cmake.org/cmake/help/latest/module/CheckCXXCompilerFlag.html
Try using hip to compile a dummy program with the flag and check whether it throws any warning.

**Comment by upsj** [comment]
fixed by https://github.com/ginkgo-project/ginkgo/pull/1409
