### ISSUE TITLE
Workflow for compiling release notes on-the-fly

### ISSUE THREAD

**Issue by upsj** [ginkgo-project/ginkgo#1192]
At the moment, somebody needs to spend a lot of time manually going through the merged PRs to write up release notes. I would suggest employing [CMake's model for semi-automatically collecting release note contents](https://github.com/Kitware/CMake/tree/master/Help/release/dev): Every PR that changes something relevant to the user creates a small (Markdown) snippet describing the change and its impact (maybe we can also separate between a short heading and a detailed description). These snippets then get concatenated to create a draft of the release notes structured into different sections, and combined and deleted with the release.

**Comment by tcojean** [comment]
Note that deal.II has another related setup but how they do it makes an even longer, not very categorized, list of changes maybe hard to go through for a user.
See this dir https://github.com/dealii/dealii/tree/master/doc/news/changes and compiled lists

**Comment by MarcelKoch** [comment]
What is the disadvantage of just updating the changelog with every relevant PR?

**Comment by upsj** [comment]
Merge conflicts every time develop gets updated

**Comment by MarcelKoch** [comment]
Wouldn't these conflicts be very small? One PR should correlate only to one bullet point in our changelog list, so the conflict can also appear in only one bullet point. That should be trivial to fix. Also, I would guess that the chance of this actually happening is rather slim.

**Comment by upsj** [comment]
If we look only at a single section inside a file, appending a line in two different branches is almost always going to lead to a merge conflict I think. It's not big, but since we have a heavily rebase-oriented workflow, I think this may make our lives easier by a lot.

**Comment by MarcelKoch** [comment]
Could you maybe link to the cmake based approach you mentioned in the beginning?

**Comment by upsj** [comment]
You can best see it in their github repository: https://github.com/Kitware/CMake/tree/master/Help/release/dev (I also added the link above)

**Comment by MarcelKoch** [comment]
Perhaps it's also interesting to see the history of their release notes to better understand this approach: https://github.com/Kitware/CMake/commits/release/Help/release/3.25.rst

**Comment by MarcelKoch** [comment]
I think that is what I mentioned above, but as @upsj points out that may lead to annoying merge conflicts during rebase.

**Comment by upsj** [comment]
While I like the idea in general, I think with the current setup it would make some things complicated, since it can't be edited easily afterwards and the GitHub merge prompt isn't well suited for composing Markdown.

**Comment by MarcelKoch** [comment]
The combined release notes would need to be edited anyway for a release, and I think we should not be editing the merge commit afterwards, or at least not in a way that changes the updates from the PR.
Again, this is just an idea and we should discuss that in a larger group at some point.

**Comment by yhmtsai** [comment]
I think tag is good.
For the file changing, if we make the merge is done by GitHub-action, we can add the information in the PR comments and let the GitHub action solve it by table. (same label or mention the pr id, just append it).
Also, we can also add the solving merge-conflict for the changelog into rebase bot, I think.
I will also prefer there's only one commit for modifying changelog.
For auto grabbing from the merge commit, we can also add the same thing with specific prefix.
like `Release-for: Deprecate ...` if they use the same description, merge them. However, it will be annoying for change the label.

**Comment by MarcelKoch** [comment]
The tags can only categorize the PR, but how would you get the actual text that should be added to the changelog from it? I guess you could again enhance the merge commit message.

**Comment by upsj** [comment]
I think the PR description might be a better place to store the changelog snippet, if we were to automate the merge process. There we have full Markdown preview and an edit history

**Comment by MarcelKoch** [comment]
Did anyone setup a repo to test/illustrate these approaches? If not, I will do that.

**Comment by MarcelKoch** [comment]
I put the stuff here: https://github.com/MarcelKoch/changelog-workflow
I didn't get to do the changelog from commit messages yet

**Comment by upsj** [comment]
I'm not sure we talked about this explicitly before, how suitable are the PR descriptions for this kind of operation? We can collect the automatically with the Github API, and even set a label based on whether a `## Changelog ` section is present at the end of the description. This allows us to defer the creation until the next release, and entries can still be edited. This would also allow us to ignore PRs that are not important to the users (internal refactoring, CI fixes etc.), but quickly see an overview of all PRs with and without changelog entries.

This approach could be a first step, since the other approaches we discussed require either changes to the repo or an automated merge process, this feels pretty non-intrusive. Thoughts?

Example for such a description snippet:

## Changelog
### New features
* The changelog can now be created automatically (#1192)
* We no longer list each PR whether they are important or not

### Interface changes
* Something something

**Comment by MarcelKoch** [comment]
@upsj I think I did something in this direction here: https://github.com/MarcelKoch/changelog-workflow/pull/9. It's missing the github actions that you mentioned, but it should be in the same spirit

**Comment by upsj** [comment]
Are we talking about the same thing here? I meant PR descriptions on Github, not merge commit descriptions.

**Comment by MarcelKoch** [comment]
Yes we are :smiley: You can make the merge commit message automatically copy the PR description. You can see that if you look into the closed PR like: https://github.com/MarcelKoch/changelog-workflow/pull/10

**Comment by MarcelKoch** [comment]
Ok, I see your issue. That makes definitely sense, I will try to see if I can work something out.

**Comment by upsj** [comment]
As as consensus from the meeting: We will start with keeping the changelog in the wiki, maybe with added automation from PR descriptions later on (but we need to make sure manual changes in the wiki don't get overwritten.

**Comment by MarcelKoch** [comment]
I've created the changelog page: https://github.com/ginkgo-project/ginkgo/wiki/Changelog
I've also added some categories for changes. Feel free to update them.

**Comment by upsj** [comment]
Seems like we have this covered, I'll close it to keep the issues cleaner
