### ISSUE TITLE
Support different allocation modes in device allocator

### ISSUE THREAD

**Issue by upsj** [ginkgo-project/ginkgo#1207]
CUDA and HIP provide functions for allocating unified memory (`cudaMallocManaged`) and pinned host memory (`cudaMallocHost`), which transparently allow access to both host and device. They might be interesting in application integrations (hybrid CPU/GPU workloads) and MPI (pinned host buffers if not GPU-aware). A first suggestion for the design would be providing `_host` and `_unified` (or `_shared`) overloads to `(raw_)alloc` and `(raw_)free`, as well as adding an enum class `allocation_type` to `ExecutorDeleter`. We could use another overload to `gko::array` taking this enum as a final parameter, to enable a straightforward integration into the rest of Ginkgo.

**Comment by MarcelKoch** [comment]
Currently, our cuda and hip executors can already allocate unified memory through the `allocation_mode` enum. By creating executors with different enums, it is also possible to switch between the different modes.

So, besides adding pinned host memory and DPCPP support, how would ginkgo, or a user of the library, benefit from these additions? Also, should these additional overloads replace the `allocation_mode` enum? I don't think having both makes sense.

**Comment by upsj** [comment]
should be fixed by #1315
