### ISSUE TITLE
pre-commit hook propagates into higher level git project

### ISSUE THREAD

**Issue by Nordegraf** [ginkgo-project/ginkgo#1223]
When using Ginkgo as a submodule the pre-commit hook is propagated into the main git repository. 
This especially applies to the [dummy hook](/ginkgo-project/ginkgo/blob/develop/third_party/dummy-hook/CMakeLists.txt), which blocks commiting to the repository, when setting the development flag for ginkgo. 

Currently I fix this in the M++ CMake file by removing the added pre-commit hook again after the script adds it using the same process for finding the git hooks location.

The script for finding the git hooks location should point to ginkgos git hooks to not block the higher level repository.

**Comment by MarcelKoch** [comment]
This indeed looks like a serious issue. Thanks for bringing that up.

**Comment by MarcelKoch** [comment]
I have created a branch that uses the fix from git-cmake-format, called `update-gcf`. Perhaps you could try it and tell us if that works out.

**Comment by Nordegraf** [comment]
That works well thank you!

Maybe a hint in the Readme would be nice, that when including Ginkgo as submodule the GINKGO_DEVEL_TOOLS and the new GCF_TOP_LEVEL_DIR should be set. Otherwise Ginkgo will still create a blocking pre-commit hook in the top level repository because of the dummy hook.

**Comment by MarcelKoch** [comment]
The branch should now be updated to also fix the dummy hook.

**Comment by Nordegraf** [comment]
That works like a charm. Thank you very much!
