### ISSUE TITLE
Merge matrix::Csr and matrix::Csri into one format

### ISSUE THREAD

**Issue by gflegar** [ginkgo-project/ginkgo#125]
Both matrix formats are actually just different implementations of the algorithms for the CSR format. While `matrix::Csr` uses the standard implementation from cuSPARSE, `matrix::Csri` can use several strategies to compute the results. Thus, the `matrix::Csr` format can be viewed as just another strategy for `matrix::Csri`, and implemented that way. Then, `matrix::Csri` should be renamed back to `matrix::Csr`.

**Comment by upsj** [comment]
This issue seems to be fixed. Feel free to reopen it if you disagree!
