### ISSUE TITLE
crash in apply() when doing 1-D matrix memory allocation

### ISSUE THREAD

**Issue by jordanpui** [ginkgo-project/ginkgo#1255]
I was using exec->apply() and encountered the following error.
Seems it crashes in allocating the memory for either rhs or locs which is a 1-D matrix.
![Snipaste_2023-01-10_17-04-37](https://user-images.githubusercontent.com/9885590/211507943-113713a7-3251-4ed9-8c4c-76d55735cedc.png)
![Snipaste_2023-01-10_17-04-00](https://user-images.githubusercontent.com/9885590/211507947-29bde9f3-e6f2-4703-896a-820cd42d26c0.png)
![Snipaste_2023-01-10_17-03-40](https://user-images.githubusercontent.com/9885590/211507948-980a2b56-556d-4ca0-8e01-1741cd51dbff.png)

**Comment by upsj** [comment]
Thanks for the report! Could you please add a bit more context to the issue? Such an allocation should normally not fail, so there might be some memory corruption happening beforehand. Can you try running it under `valgrind` and see if you get any previous errors before the solve?

**Comment by jordanpui** [comment]
seems it's due to memory leakage elsewhere in the program
