### ISSUE TITLE
different allocation result using get_values()[i] and at(i,1) on 1-D matrix

### ISSUE THREAD

**Issue by jordanpui** [ginkgo-project/ginkgo#1256]
I observed different allocation results using get_values()[i] and at(i,1) on 1-D matrix, whose type is gko::matrix::Dense<double.
Seems the index is one off compared to the other. That is having the following code
for (unsigned i = 0; i < m; i++) {
  rhs->get_values()[i] = i;
}
for (unsigned i = 0; i < m; i++) {
 std::cout << i << " " << rhs->get_values()[i] << " " << rhs->at(i, 1) << std:: endl;
}

it will output 
0 0 1
1 1 2

If I do it other way around

it will output
0 -19929131 0
1 0 1
2 1 2

**Comment by upsj** [comment]
Ginkgo uses 0-based indexing, maybe you are used to 1-based indexing? This should be `rhs->at(i, 0)`

**Comment by jordanpui** [comment]
sorry for this silly mistake

**Comment by upsj** [comment]
No worries, I'm happy this could be resolved so easily!

**Comment by jordanpui** [comment]
Sorry that I have another minor question, do this two methods have the same efficiency for 1-D dense matrix?

**Comment by upsj** [comment]
They should (at least with an optimizing compiler) lead to equivalent code generation, but that may change in the future. And as always with performance optimization: if you are in doubt, try to benchmark it (as long as the runtimes are long enough that you can get reliable timings)
