### ISSUE TITLE
Refactor matrix::Csri

### ISSUE THREAD

**Issue by gflegar** [ginkgo-project/ginkgo#126]
There are some parts of CUDA `matrix::Csri` that are done in an suboptimal way using flow control, instead of relying on polymorphism to achieve the same behavior, and should be improved.

In addition, some parts of CSR-I and COO implementation are very similar and it should be possible to share the same code.

**Comment by hartwiganzt** [comment]
@gflegar please specify. I don't think this statement helps @yhmtsai.

**Comment by upsj** [comment]
This issue seems to no longer apply. Feel free to reopen it if you disagree!
