### ISSUE TITLE
Improve implementation of standard (imbalanced) CSR SpMV

### ISSUE THREAD

**Issue by gflegar** [ginkgo-project/ginkgo#127]
Our current GPU implementation of the standard (imbalanced) CSR SpMV uses what is known as a "scalar" implementation of the CSR format. There is also an alternative implementation usually known as the "vector" kernel. See [Bell & Garland](https://www.nvidia.com/docs/IO/77944/sc09-spmv-throughput.pdf). In fact, a combination of both, depending on the matrix is usually the best performing row-based parallelization of CSR SpMV for balanced matrices, where the "vector" size is adapted to the nonzero distribution. More advanced versions even split the matrix in multiple parts, and use different lengths for them, as is done in [ViennaCL](http://viennacl.sourceforge.net/viennacl-about.html)'s "CSR adaptive".

**Comment by upsj** [comment]
It looks to me like this issue has been solved a long time ago (our classical CSR uses one subwarp instead of one thread per row). @yhmtsai can you confirm this?

**Comment by yhmtsai** [comment]
Yes, we use subwarp per row for classical CSR
