### ISSUE TITLE
Variable number of iterations needed for convergence (for selected scenarios)

### ISSUE THREAD

**Issue by stanisic** [ginkgo-project/ginkgo#1293]
Hi,

When running Ginkgo 1.5 solver BENCHMARK with varying benchmark parameters using OpenMP executor on 5 different machines (Arm and x86 architectures), I have realized that for some setups the number of iterations needed to converge is very different for repeated experiments. Consequently, the overall performance of the whole run also varies. Is such behavior expected? If yes, why is it happening and is it related only to a subset of preconditioners/solvers/formats? At the meeting with selected Ginkgo developers, I have learned that parilu/paric/-isai preconditioners and ell/hybrid formats are perhaps more susceptible to this.

Here is one scenario where I can clearly see this impact (on AMD Milan number of iterations varies between 6 and 194):
```
Matrix=consph.mtx(https://sparse.tamu.edu/Williams/consph); PRECONDS=parilu; SOLVERS=cb_gmres_reduce1; FORMATS=ell
```

Another scenario where the variability is not as high, but still reproducible, and which uses jacobi preconditioner (on AMD Milan number of iterations varies between 895 and 997):
```
Matrix=offshore.mtx(https://sparse.tamu.edu/Um/offshore); PRECONDS=jacobi; SOLVERS=cgs; FORMATS=hybrid
```

For reproducibility here is the rest of my setup, although I doubt that any of these parameters play an important role:
```
Ginkgo version: Release 1.5
Compiler: GCC 12.2.0
export OMP_NUM_THREADS=96 (or whatever is the max number of cores on the selected machine)
export OMP_PROC_BIND=spread
export OMP_PLACES="cores"
CMake config: cmake -G "Unix Makefiles" -DGINKGO_BUILD_EXTLIB_EXAMPLE=OFF -DGINKGO_BUILD_EXAMPLES=OFF -DGINKGO_BUILD_TESTS=OFF -DGINKGO_BUILD_HWLOC=ON -DCMAKE_BUILD_TYPE=Release -DGINKGO_BUILD_BENCHMARKS=ON  -DCMAKE_INSTALL_PREFIX=$PWD ..
Benchmark parameters: BENCHMARK=solver; EXECUTOR=omp; SOLVERS_MAX_ITERATIONS=10000, SOLVERS_PRECISION=1e-6, double precision and other defaults...
OS: Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-139-generic)
Architectures: Arm (aarch64) and x86 (x86_64). 
```

Best,
Luka from Huawei Munich Research Center

**Comment by MarcelKoch** [comment]
Hi @stanisic. I can comment at least on the first case. That one uses our `Ilu` preconditioner with the `ParIlu` factorization. This combination does not result in a deterministic preconditioner. The ParIlu does a fixed number of iterations to approximate the correct ILU decomposition, but since there is no synchronization between iterations, the approximation might not be good. In fact, you can run into non-convergence with this combination, even for problems where the correct ILU factors lead to convergence. So that variability might be expected there.

**Comment by MarcelKoch** [comment]
I've checked the second example, and that seems to not really converge. For me, it stops at 894 iterations (consistently), but by looking at the detailed output there are some NaNs in there, so I don't think we can expect deterministic results for this particular case.

**Comment by stanisic** [comment]
Thanks for the quick reply.  So apart from using the `parilu` preconditioner option, what are the other preconditioners/solvers/formats combinations that may be non-deterministic for certain matrices?

**Comment by upsj** [comment]
`paric`, `parilut` and `parict` come to mind, and the `idr` solver chooses a random subspace, so this may also influence determinism.
There is a tiny amount of non-determinism in some of our matrix formats, but that should be smoothed out by the solver convergence.

**Comment by stanisic** [comment]
OK, thank you both for the answers, this is clear for me now.
