### ISSUE TITLE
Target METIS::METIS not found

### ISSUE THREAD

**Issue by lahwaacz** [ginkgo-project/ginkgo#1308]
A project with `find_package(Ginkgo)` fails with Ginkgo installation from the `develop` branch:

```
-- Configuring done
-- Generating done
CMake Error at /usr/local/lib/cmake/Ginkgo/GinkgoTargets.cmake:115 (set_target_properties):
  The link interface of target "Ginkgo::ginkgo" contains:
    METIS::METIS
  but the target was not found.  Possible reasons include:
    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
Call Stack (most recent call first):
  /usr/local/lib/cmake/Ginkgo/GinkgoConfig.cmake:235 (include)
  CMakeLists.txt:61 (find_package)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by upsj** [comment]
Can you take a look at the installed GinkgoConfig.cmake? What does it specify for `GINKGO_HAVE_METIS`? Because this should already fail earlier if it was inconsistent, maybe I made a typo?

**Comment by upsj** [comment]
@lahwaacz can you try the linked PR?

**Comment by lahwaacz** [comment]
It failed in our CI job where we install Ginkgo from source to test the integration. So I can't easily look into the `GinkgoConfig.cmake` file, but I can try to build from the other branch...

**Comment by upsj** [comment]
I'm surprised that this didn't come up in our own CI, is this a static library build?

**Comment by lahwaacz** [comment]
Shouldn't be, it's just this `before_script` for GitLab CI:

```yaml
    before_script:
        - !reference [.env_setup, script]
        # clone and build Ginkgo
        - git clone https://github.com/ginkgo-project/ginkgo.git
        - cmake -B "./build_ginkgo/$CI_JOB_NAME" -S "ginkgo" -G Ninja
                -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
                -DGINKGO_BUILD_TESTS="no"
                -DGINKGO_BUILD_EXAMPLES="no"
                -DGINKGO_BUILD_BENCHMARKS="no"
        # "install" implies the "all" target
        - ninja -C "./build_ginkgo/$CI_JOB_NAME" ${NINJAFLAGS} install
```

Metis is installed in the container (Arch Linux).

**Comment by upsj** [comment]
Is it possible the FindMETIS script found a static library of METIS? That would explain why we don't see the issue, we only have a shared METIS library in our containers AFAIK

**Comment by upsj** [comment]
Can you share a few more details about how you built the container, so I can reproduce this? (probably not this week though, LMK if it's important to fix this immediately)

**Comment by lahwaacz** [comment]
Fixed on our side in https://gitlab.com/tnl-project/tnl/-/commit/8842281d003f0593494521b84eebfcbe90fd51e7. I'm sorry for the noise :pray:
