### ISSUE TITLE
CMake Warning in GinkgoConfig.cmake on Windows

### ISSUE THREAD

**Issue by Destranix** [ginkgo-project/ginkgo#1359]
```
CMake Warning (dev) at D:/My_Programs/Ginkgo/lib/cmake/Ginkgo/GinkgoConfig.cmake:90:
  Syntax Warning in cmake code at column 53

  Argument not separated from preceding token by whitespace.
```

It's following line:
`set(GINKGO_CUDA_HOST_COMPILER C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.34.31933//bin/Hostx64/x64/cl.exe)`

Seems like the path needs to be in quotes due to its whitespaces

**Comment by upsj** [comment]
Thanks for the report, we were missing some quotes.
