### ISSUE TITLE
Build errors with CUDA enabled

### ISSUE THREAD

**Issue by pratikvn** [ginkgo-project/ginkgo#138]
I am having build issues when the BUILD_CUDA flag has been enabled. 

This is a part of the error i get:

`````
../../../cuda/libginkgo_cuda.so: undefined reference to `gko::matrix::Dense<double>::move_to(gko::matrix:
:Ell<double, int>*)'
../../../cuda/libginkgo_cuda.so: undefined reference to `non-virtual thunk to gko::matrix::Dense<float>::
move_to(gko::matrix::Ell<float, int>*)'
../../../cuda/libginkgo_cuda.so: undefined reference to `non-virtual thunk to gko::matrix::Dense<float>::
move_to(gko::matrix::Sellp<float, long>*)'
../../../cuda/libginkgo_cuda.so: undefined reference to `gko::matrix::Dense<double>::convert_to(gko::matr
ix::Sellp<double, int>*) const'
../../../cuda/libginkgo_cuda.so: undefined reference to `non-virtual thunk to gko::matrix::Dense<std::com
plex<double> >::write(gko::matrix_data<std::complex<double>, long>&) const'
../../../cuda/libginkgo_cuda.so: undefined reference to `gko::matrix::Dense<std::complex<float> >::conver
t_to(gko::matrix::Sellp<std::complex<float>, long>*) const'
``````

I am compiling with gcc 6.4.0 and CUDA V9.0.176 and have the same problem with CUDA 9.1 as well. The problem seems to occur after it tries to link the executable exception, but might not be related to that specifically.

**Comment by tcojean** [comment]
This is really weird. I had that problem earlier and after trying to debug it I cannot get it anymore. I cannot say what happened. I could not find any proper solution for this.

**Comment by gflegar** [comment]
Is this with a clean build?

**Comment by tcojean** [comment]
We tried  various things, even with a new repo Pratik still gets this problem.

**Comment by gflegar** [comment]
Can you attach the full build log of a clean build with the errors?

**Comment by pratikvn** [comment]
The Cmake and the make outputs.

[CMakeCache.txt](https://github.com/ginkgo-project/ginkgo/files/2419260/CMakeCache.txt)
[error.log](https://github.com/ginkgo-project/ginkgo/files/2419261/error.log)

**Comment by gflegar** [comment]
Just to double check:
*   You're using the newest version of Ginkgo, with a clean working tree: `git fetch; git status` says:
    > On branch develop
    > Your branch is up to date with 'origin/develop'.
    > 
    > nothing to commit, working tree clean

*   The build was cleaned by removing the whole build directory, and re-generating the build system, and not by just doing `make clean` (that one doesn't always do what you would expect it to)

Make sure that everything above is true if it's not already, and this time build with the command `make VERBOSE=1` and attach the result (and don't add the `-j` flag, will take quite a bit longer, but the output will be easier to interpret).

Also, there's no output attached above from the `cmake` step, only the `CMakeCache.txt` and the output of `make`.

Thanks.

**Comment by pratikvn** [comment]
Yes, with a a clean build and a newest version of Ginkgo from the gitlab repo.

cmake command: 
```
cmake -DBUILD_TESTS=on -DBUILD_OMP=on -DBUILD_CUDA=on -DCMAKE_INSTALL_PREFIX=/home/pratik/Documents/00git/private_ginkgo/new_ginkgo/install ../ginkgo/
```
Output:
[cmake_output.txt](https://github.com/ginkgo-project/ginkgo/files/2419691/cmake_output.txt)

make command:

```
make VERBOSE=1
```

[make_output.txt](https://github.com/ginkgo-project/ginkgo/files/2419693/make_output.txt)

**Comment by gflegar** [comment]
This is your PC or the Jetson card?

**Comment by pratikvn** [comment]
My PC.

**Comment by pratikvn** [comment]
Okay, I think I have narrowed the error down to this commit: 00becbf2b3bf4b47d2d827292a830745d3440df5 . It seems that something here, possibly `rapidjson` seems to be creating the problem. 

If I go forward to `develop` and build with `BUILD_BENCHMARKS=off` everything seems to run fine. So, in a broad sense, the problem seems to be with building benchmarks.

**Comment by gflegar** [comment]
Ok, I don't get how this happens. I mean, the error doesn't have anything to do with benchmarks....

**Comment by pratikvn** [comment]
Yes, it is very weird. It is also possible that some settings from my system interferes with the benchmarks linking, particularly with rapidjson as no one else seems to be able to reproduce the problem.

**Comment by gflegar** [comment]
Maybe try checking (using `make VERBOSE=1`) what's the difference between build commands with and without `BUILD_BENCHMARKS` enabled.
It could be possible that rapidjson's cmake configuration somehow interferes and modifies ours...

**Comment by pratikvn** [comment]
After a bit of digging, I found out that the error does not have anything to do with `BUILD_BENCHMARKS` but with the fact that `BUILD_BENCHMARKS` builds with "DebugRelease" mode. So, I tried it out separately with `-DCMAKE_BUILD_TYPE = Debug` and `DCMAKE_BUILD_TYPE= Release`. It seems that the problem is with the release mode when the optimization flags are added. With no optimization flags, it works fine. Have tested that this problem occurs for CUDA 9.0 with gcc 6.4 and for CUDA 9.1 with gcc 7.3 and gcc 6.4 on two different machines.

**Comment by pratikvn** [comment]
After a bit of digging, I found out that the error does not have anything to do with `BUILD_BENCHMARKS` but with the fact that `BUILD_BENCHMARKS` builds with "DebugRelease" mode. So, I tried it out separately with `-DCMAKE_BUILD_TYPE = Debug` and `DCMAKE_BUILD_TYPE= Release`. It seems that the problem is with the release mode when the optimization flags are added. With no optimization flags, it works fine. Have tested that this problem occurs for CUDA 9.0 with gcc 6.4 and for CUDA 9.1 with gcc 7.3 and gcc 6.4 on two different machines.

**Comment by tcojean** [comment]
I get the same error reliably on the containers I am configuring for our CI system. Just as Pratik, this happens only with `DCMAKE_BUILD_TYPE=Release` (optimizations of some sort) activated. This only seems to concern functions potentially found in `dense.cpp` notably all conversions, write function, etc.

**Comment by gflegar** [comment]
Let's try to rule out CMake compiler detection problems. Assuming you have paths to the C, C++ and CUDA compiler binaries set in `${CC}`, ${CXX}` and `${CUDA}` variables, respectively, add the following options to the `cmake` command line (make sure you do a clean generate and build, to avoid using existing CMake cache):

```
-DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_CUDA_COMPILER=${CUDA} -DCMAKE_CUDA_HOST_COMPILER=${CXX}
```

See if the linking problems still happen.

**Comment by thoasm** [comment]
I get the same error on my PC at home when compiling the current state of the develop branch (commit 474a6f226d87539b3a7c586052b1a600bef10a9c) in Release mode, but not in Debug mode. This is with a completely clean `cmake` and `make`.
`nvcc --version` is `Cuda compilation tools, release 9.0, V9.0.176`
and `gcc --version` is 7.3.0

cmake command:
```bash
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DDEVEL_TOOLS=ON \
-DBUILD_TESTS=ON -DBUILD_REFERENCE=ON -DBUILD_OMP=ON -DBUILD_CUDA=ON \
-DCMAKE_INSTALL_PREFIX=/home/thomas/projects/ginkgo_installed
```
CMake output:
[cmake_output.txt](https://github.com/ginkgo-project/ginkgo/files/2745467/cmake_output.txt)

`make VERBOSE=1` output:
[make_output.txt](https://github.com/ginkgo-project/ginkgo/files/2745468/make_output.txt)

It looks very similar to #194, but happens only in Release mode on my PC.
