### ISSUE TITLE
Use of C++17 Atomic Exchange Causes Compilation Error with C++20

### ISSUE THREAD

**Issue by jbadwaik** [ginkgo-project/ginkgo#1401]
I'm trying to compile ginkgo with C++20, and I get the following error due to [this line](https://github.com/ginkgo-project/ginkgo/blob/3d396152217bbb94de69926ae075e5e2a98b120c/omp/reorder/rcm_kernels.cpp#L235). 

```
error: ‘memory_order_acq_rel’ is not a member of ‘std::memory_order
```
This happens due to two things:
1. C++ made the memory order enum strongly typed in C++20 and hence changed the naming to prevent accidental usage.
2. The code in the link above [depends on](https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html#index-_005f_005fatomic_005fcompare_005fexchange_005fn) implicit conversion of weakly-typed `enum` to `int`. 

A fix would be to replace all occurrences of memory order with the newer version for newer language modes. There are a couple of ways I can think of to approach this:
1. Define a memory order macro, something like
```
#ifdef CPP20
#define MEMORY_ORDER_RELAXED std::memory_order::relaxed
#else 
#define MEMORY_ORDER_RELAXED std::memory_order::memory_order_relaxed
#endif
```
2. Replace call sites of all functions with an `#ifdef` everywhere.

**Comment by upsj** [comment]
Thanks for highlighting this issue. We should probably be able to use OpenMP atomic pragmas instead, which also increases portability. I've been working on some other concurrent algorithms in Ginkgo OpenMP, so I'll tackle that soon.

**Comment by jbadwaik** [comment]
Thank you for taking a look at this. 
Someone pointed out to me that using `std:: memory_order_acq_rel` instead of `std::memory_order:: memory_order_acq_rel` should do the trick for both language modes without needing the `#ifdef`s. 

May be that is a more palatable quick-fix solution.
