### ISSUE TITLE
CURAND generators not destroyed

### ISSUE THREAD

**Issue by Destranix** [ginkgo-project/ginkgo#1406]
Not sure if destruction is necessary, the API reference does not state that. But it has a function for destruction of generators and on my device I'm getting an a curand allocation exception after a couple of iterations of Idr solver with Cuda executor.

**Comment by yhmtsai** [comment]
Thanks for reporting it!
I add the destroy function in the branch destroy_curand https://github.com/ginkgo-project/ginkgo/tree/destroy_curand
Could you check whether it works for you or not?

**Comment by Destranix** [comment]
"Could you check whether it works for you or not?"

Curently not. Got some stressing deadline and no time to rebuild the project. But I will keep the E-Mail, so maybe in a couple of monts I can retry.
