### ISSUE TITLE
How to run preconditioned solver example on HPC

### ISSUE THREAD

**Issue by acse-bn20** [ginkgo-project/ginkgo#1442]
Hi,

I am trying to use ginkgo. As a first step, I would like to run the preconditioned solver from the example file on CUDA. Ginkgo has already been built by the HPC support. When I load the module and compile it, I get some errors. I was wondering what the mistake might be.

//necessary modules for ginkgo -- copied requirements from the documentation of the HPC server
module load StdEnv/2020
module load gcc/11.3.0
module load openmpi/4.1.4
module load cuda/11.7
module load ginkgo/1.6.0
```

gcc -std=c++14 ginkgo_test.cpp -o ginkgo -I/ginkgo/include -lginkgo_cuda
./ginkgo "cuda"


```
This results in the attached file.
[slurm-12300254.log](https://github.com/ginkgo-project/ginkgo/files/13167546/slurm-12300254.log)

**Comment by tcojean** [comment]
Note that if you do not use CMake, you can also use pkg-config to extract the flags as that should be installed as well together with the source files. This should be stored within a `ginkgo.pc` file.

**Comment by acse-bn20** [comment]
Thank you for both of you. I am trying to follow the CMake approach, but I am getting some cmake error and trying to fix those.

**Comment by acse-bn20** [comment]
@MarcelKoch I run your example but I got very similar result compared to when I tried compile the source file for myself. I am not sure it is me or the installation might be causing the issue. 

[slurm-12300254.log](https://github.com/ginkgo-project/ginkgo/files/13168208/slurm-12300254.log)

**Comment by MarcelKoch** [comment]
What is the file you are compiling? You mentioned that you're looking into our preconditioned-solver example. If that is what you are using, from which version of Ginkgo is it?

**Comment by acse-bn20** [comment]
This is what I am trying to compile: https://github.com/ginkgo-project/ginkgo/blob/develop/examples/preconditioned-solver/preconditioned-solver.cpp and from the latest release. On the server, I have ginkgo 1.6.0.

**Comment by MarcelKoch** [comment]
You need to use the file from the 1.6.0 release: https://github.com/ginkgo-project/ginkgo/blob/v1.6.0/examples/preconditioned-solver/preconditioned-solver.cpp
We made some changes after that release which are not backward compatible, i.e. code written for Ginkgo 1.7.0 won't run with a Ginkgo 1.6.0 library.

**Comment by acse-bn20** [comment]
That resolved the problem. Thank you very much!
