### ISSUE TITLE
What value(s) should RelativeResidualNormReduction log?

### ISSUE THREAD

**Issue by tcojean** [ginkgo-project/ginkgo#146]
There is an issue concerning the RelativeResidualNormReduction stopping criterion. The main problem is that the value returned (logged) makes sense only when considering the initial one, and this can be confusing, it at least is for deal.II which is not used to this model.

### What we do
Currently, we return the final residual norm that we got once the residual norm reduction process has finished.

### Concrete Example
As an example, let's consider the initial residual norm is `10` and we want to reduce it by `1e-10`. The final value that will be logged will be of the order of `1e-9`.

### Alternative to discuss
What we could do would be to instead log the normalized residual norm, that is with the previous example `1e-9/10` which would give us something of the order of `1e-10`. This value would now represent by how much we actually reduced the residual norm, instead of the current residual norm that we got to.

What do you think about this? I personally think this would make things simpler and fit the name of the stopping criterion (which is to reduce a residual norm by a certain amount) as we would then know by how much we reduced the residual norm. The problem is we may still need the final residual norm somewhere and integrating this can be hard (in terms of staying generic).

**Comment by gflegar** [comment]
I think it's fine the way it is, and doing the thing you suggest would break the semantics of the interfaces. Thus, I vote against this.

Here is my reasoning:

The stopping criterion logs the residual norm - and the final residual norm in your example will be `1e-9`. There's nothing wrong with it. If you're requesting the _relative_ norm reduction, then you should be aware that requesting `1e-10` won't give you the final residual on the order of magnitude of `1e-10`.

What if we add a new stopping criterion? Say `AbsoluteResidualNormReduction`. What should that one pass to the logger? Also the relative norm? This does not fit the name of this stopping criterion. And if it returns the absolute norm, then you're basically breaking the [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle).

The point here is: there should be a well defined interface between object hierarchies (in this case Criteria and Loggers). Any pair of objects from the two hierarchies should semantically respect that interface and not change the meaning of the messages. This is the only way to achieve semantic polymorphism.

If the user wants to get the relative residual norm, it is not that difficult. They have the matrix, the right hand side, and the initial guess, so there's no problem in computing the initial residual norm `r0 = ||Ax0 - b||`. Then they can just divide the output of the logger with `r0` and get the relative norm.

**Comment by tcojean** [comment]
Locked with #148
