### ISSUE TITLE
Ginkgo uses obsolete C++ bindings for MPI

### ISSUE THREAD

**Issue by lahwaacz** [ginkgo-project/ginkgo#1462]
Ginkgo uses `find_package(MPI 3.1 COMPONENTS CXX)` in many places, e.g. https://github.com/ginkgo-project/ginkgo/blob/develop/cmake/autodetect_executors.cmake#L18

This requests the C++ bindings for MPI, which were however removed from the [MPI 3.0 standard (see section 1.6)](https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report.pdf). Implementations took their time with this removal, e.g. OpenMPI removed their C++ bindings only in [version 5.0](https://docs.open-mpi.org/en/v5.0.x/news/news-v5.0.x.html). Hence, Ginkgo can't be built with OpenMPI 5.0.

**Comment by yhmtsai** [comment]
Thanks for reporting!
We only change the binding from C++ to C in https://github.com/ginkgo-project/ginkgo/pull/1306 but still request CXX component.
From CMake https://cmake.org/cmake/help/latest/module/FindMPI.html, `CXX` component refers to C API useable by C++, which should be our case. `MPICXX` components is the removed one in MPI-3.
Could you share the CMake error message?

**Comment by lahwaacz** [comment]
You're right, the `CXX` component is fine. The error message I saw was:
```
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS)
-- Could NOT find MPI (missing: MPI_CXX_FOUND CXX)
-- Looking for HWLOC - found version 2.8.0
-- Looking for hwloc_topology_init
-- Looking for hwloc_topology_init - found
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) (Required is at least version "3.1")
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_CXX_FOUND CXX) (Required is at least
  version "3.1")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindMPI.cmake:1837 (find_package_handle_standard_args)
  /usr/lib/cmake/Ginkgo/GinkgoConfig.cmake:192 (find_package)
  CMakeLists.txt:48 (find_package)


-- Configuring incomplete, errors occurred!
```
But when I deleted the CMake cache and started from scratch, it worked... So Ginkgo works fine with OpenMPI 5.0, I'm sorry for the noise :angel:
