### ISSUE TITLE
CPU mem allocate failure for matrix csr dim greater than 300k

### ISSUE THREAD

**Issue by uboats** [ginkgo-project/ginkgo#1468]
I have many matrix with dim greater than 300k, then i got below failure for ref/OMP constantly
terminate called after throwing an instance of 'gko::AllocationError'
  what():  /home/abc/ginkgo-git/core/base/memory.cpp:20: cpu: failed to allocate memory block of 1247672335776B

I used IndexType long int, ValueType double

**Comment by upsj** [comment]
Can you please provide some more information? Which matrix format are you using? Can you share your matrix? What is the full backtrace (run `gdb ./your_application your parameters` and type `bt` once the exception occurred)? It seems like somewhere an index/offset calculation is running completely out of bounds (this is more storage than would be required for storing the elements in Dense format)

**Comment by uboats** [comment]
Hi,
It happened in ilu_gmres->apply(b, x);
I attached the matrix, please rename it to xxx.bz2 file
[ginkgo1.mtx.bz2.zip](https://github.com/ginkgo-project/ginkgo/files/13454683/ginkgo1.mtx.bz2.zip)

**Comment by upsj** [comment]
What is your krylov_dim in GMRES?

**Comment by uboats** [comment]
ahhh, i think i need to just set it same as maxiter
let me try

**Comment by upsj** [comment]
That definitely works, we allocate a matrix of size `num_rows * krylov_dim` for storing the Krylov basis vectors, so that may lead to huge storage requirements if you set it to `num_rows` as well
