### ISSUE TITLE
Check memory access quality of the CUDA executor

### ISSUE THREAD

**Issue by tcojean** [ginkgo-project/ginkgo#152]
```
1/16 MemCheck: #72: cuda/test/base/cuda_executor .....................   Defects: 5
3/16 MemCheck: #74: cuda/test/matrix/coo_kernels .....................   Defects: 75
4/16 MemCheck: #75: cuda/test/matrix/csr_kernels .....................   Defects: 101
5/16 MemCheck: #76: cuda/test/matrix/dense_kernels ...................   Defects: 75
6/16 MemCheck: #77: cuda/test/matrix/ell_kernels .....................   Defects: 3
7/16 MemCheck: #78: cuda/test/matrix/hybrid_kernels ..................   Defects: 3
8/16 MemCheck: #79: cuda/test/matrix/sellp_kernels ...................   Defects: 3
9/16 MemCheck: #80: cuda/test/preconditioner/block_jacobi_kernels ....   Defects: 75
10/16 MemCheck: #81: cuda/test/solver/bicgstab_kernels ................   Defects: 75
11/16 MemCheck: #82: cuda/test/solver/cg_kernels ......................   Defects: 75
12/16 MemCheck: #83: cuda/test/solver/cgs_kernels .....................   Defects: 75
```

and the last 4 tests fail under memcheck. Someone will have to take a look into it at some point, as at least some of the defects are probably false-positives. Specifically, the 101 and 75 may also come from cuda libraries, but are not filtered properly.

_Originally posted by @gflegar in https://github.com/ginkgo-project/ginkgo/pull/149#issuecomment-429877929_

**Comment by tcojean** [comment]
I am forced to reopen this. I do not know what happened. We were down to 80 valgrind warnings and starting with #232 we have around 6K new valgrind problems. They are all related to a `unique_ptr` not being freed for some reason, so only one thing should need fixing.
See [here](https://my.cdash.org/viewDynamicAnalysis.php?buildid=1617511)

**Comment by tcojean** [comment]
I looked into it but still cannot find a solution. The problem always comes from all of our calls to `l{...}` in our tests inside the `GKO_ASSERT_MTX_NEAR` macros. More precisely, in the `gko::initialize` function which creates two dense matrix. The first matrix call allocates the memory space and stores the result inside an array. The matrix is then `std::move`d to the second one (which has the extra user parameters) before being returned. According to valgrind, an the space allocated for the array is not properly freed now. I am still unsure if that is because the `move` did not go through properly and we have two memory spaces, or if we only have one left and that one is never freed for whatever reason (probably the array does not have the proper `executor_deleter`.

**Comment by hartwiganzt** [comment]
If you roll back before #232, the memory leaks disappear?

**Comment by pratikvn** [comment]
The main changes of #232 should be these:
1. Adding static asserts. (I dont think this causes any problems)
2. Changing some loop index types to `size_type`(This should also not a a problem.)
3. Change the variadic macros and add duplicates (Not sure about this.)
4. Reorder the initialization of the member variables for the `-Wreorder` warnings. ( Maybe this is the problem, because the [`data_manager`](https://github.com/ginkgo-project/ginkgo/blob/1e37ad4bfa66e0bf04248d9006def183984fb3ae/include/ginkgo/core/base/array.hpp#L435) is a `unique_pointer`. See the changes to the file [here](https://github.com/ginkgo-project/ginkgo/pull/232/files#diff-b4c84987fd0d3378815e6b661500d049) ).

**Comment by tcojean** [comment]
Thanks Pratik for the summary, indeed as you were thinking the reordering seems to cause this problem. Reverting that part of #232 seems to fix the detected memory leaks. I will try to keep a proper ordering without the memory leaks.

**Comment by tcojean** [comment]
Alright, when paying attention to the code the problem seems obvious:
```c++
exec_(std::move(exec)),
          num_elems_(num_elems),
          data_(nullptr, default_deleter{exec})
```

exec is `std::move`d and later passed to the default_deleter, which means exec here has value `nullptr` (`std::move` sets nullptr after moving, because the variable is unusable).
