### ISSUE TITLE
HIP platform detection with hipconfig is not sufficient

### ISSUE THREAD

**Issue by lahwaacz** [ginkgo-project/ginkgo#1565]
`cmake/hip.config` contains some code to auto-detect `hipconfig` location:

https://github.com/ginkgo-project/ginkgo/blob/f952c6eb1c0bb79b68f1c7ec03e5f20052f72d48/cmake/hip.cmake#L109-L124

However, at the top of this file, either `HIP_PLATFORM` envvar or `GINKGO_HIPCONFIG_PATH` cmake variable is required:

https://github.com/ginkgo-project/ginkgo/blob/f952c6eb1c0bb79b68f1c7ec03e5f20052f72d48/cmake/hip.cmake#L1-L9

The [documentation](https://github.com/ginkgo-project/ginkgo/blob/develop/INSTALL.md#hip-platform-detection-of-amd-and-nvidia) also says that the HIP platform is auto-detected and does not mention `GINKGO_HIPCONFIG_PATH` at all.

**Comment by upsj** [comment]
This will likely be made redundant by #1334
