### ISSUE TITLE
Consolidate cuda matrix descriptors

### ISSUE THREAD

**Issue by hartwiganzt** [ginkgo-project/ginkgo#163]
Similar to the cuda handle ( #161 ) , every cusparse operation with a sparse matrix requires a cusparse MatDescriptor. Currently, we initialize the matrix descriptor prior to the cusparse call and destroy it afterwards. Maybe we should move this to the linear operator. However, we need to be careful not to pollute the classes...

**Comment by upsj** [comment]
Creating the cusparse handle never showed up as any performance concern, and is only necessary for specific operations (transpose, spgemm, spgeam, sparselib SpMV) that may not be used at all in a solver. So I think we can ignore this suggestion.
