### ISSUE TITLE
Ginkgo v1.8.0: test/mpi/matrix.cpp", line 220: error: too many initializer values

### ISSUE THREAD

**Issue by almaeder** [ginkgo-project/ginkgo#1638]
I want to compile v1.8.0 with nvc++ from nvida_hpc_sdk 23.9.
When compiling:
[ 74%] Building CXX object test/mpi/CMakeFiles/test_mpi_matrix_omp.dir/matrix.cpp.o    
the following errors are thrown:
/test/mpi/matrix.cpp", line 220: error: too many initializer values                                                                                                                
          {{size_local[0], {{0, 0, 2}}},       

line 221: error: too many initializer values
           {size_local[1], {{0, 1, 5}}},

**Comment by upsj** [comment]
Can confirm this issue, we don't test nvhpc with MPI, so it doesn't come up in our pipelines
