### ISSUE TITLE
Reducing the amount of warnings

### ISSUE THREAD

**Issue by tcojean** [ginkgo-project/ginkgo#174]
This is a summary of the discussion which rose during PR #168. This is a mix of @gflegar's contributions and mine.

There are currently a lot of warnings generated when compiling Ginkgo with the flags `-Wall -Wextra -pedantic`. Most of them are part of two categories, either unused arguments or an extra `;` mostly due to putting a `;` after a macro call which doesn't end in a typical statement.

Here is a summary with GCC 8.2.0
```bash
$ make clean
$ make 2> warnings                                     # without CUDA
$ cat warnings | grep -e "\[-[Wp]" | wc -l       # try to get only the [-W or [-p header for warnings
  25447
$ cat warnings | grep "unused-parameter" | wc -l
  15226
$ cat warnings | grep "extra ‘;’" | wc -l
  9301
# Note that over 900 warnings are not part of either of those
```

### The extra ';' warnings
`;` is defined as a null statement, and as such can appear anywhere where a statement can and should be ignored by the compiler. The problem with macros is that they can either define a complete statement (as in `#define F f() {}`), or just a prefix which has to be followed by a statement or used in an expression `#define F f()`. Using the former without a semicolon can cause confusion as it is not clear if code like `F G` means that `G` is used to complete the definition generated by `F`, or if they are two separate macros. On the other hand, always following a macro with a semicolon (even when it is not needed) clarifies this: `F; G;` are two separate statement and `F G;` signifies that `F` modifies the definition of `G`.

The question is what is more important: making clear the meaning of the macro, or making sure there are no false-positive compiler warnings.

One option could be to declare a function after macros that define a full statement. The following code compiles without warnings with both `clang++ -Wall -Wextra -pedantic -std=c++11` and `g++ -Wall -Wextra -pedantic -std=c++11`:

```c++
#define F void f() {} void __gko_macro_terminator__()
#define G void g() {} void __gko_macro_terminator__()
#define S struct S { int x; } s; void __gko_macro_terminator__()

S;
F;
G;

int main() {
    f();
    auto gx = s.x;
    S;
    auto lx = (s.x = 0);
    return gx + lx;
}
```

Note that for some of the current macros this would also mean polluting some of the class's public methods space.

**Comment by pratikvn** [comment]
Here is the current list of warnings (Solutions to be updated soon):

+ [ ] `warning: extra ; ignored` : False positive `;` warnings.
     Solution: To be fixed with adding an function that defines a full statement (example above).
+ [ ] `warning: inheriting constructors must be inherited from a direct base class`
    Solution: 
+ [ ] `warning: ISO C++11 requires at least one argument for the "..." in a variadic macro`
    Solution: Ignore for now. Supposed to be [fixed](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0306r4.html) in C++2a 
+ [ ] `warning: unused parameter ` 
    Solution:
