### ISSUE TITLE
Should we emit iteration_complete for last iteration

### ISSUE THREAD

**Issue by gflegar** [ginkgo-project/ginkgo#187]
Currently the `iteration_complete` event is not emitted for the last iteration of the solver (i.e. for the iteration where we converged). See [CG](https://github.com/ginkgo-project/ginkgo/blob/develop/core/solver/cg.cpp#L112) for an example.
This causes some loggers (e.g. the residual logger we use in benchmarks) to not output the residuals for the final iteration.

Should we consider this a bug, and emit the event for the final iteration?

**Comment by hartwiganzt** [comment]
@gflegar please elaborate, I don't understand yet.

**Comment by gflegar** [comment]
If you converge in 3 iterations, you only get 2 events - for iterations 1 and 2, but not for iteration 3.

**Comment by hartwiganzt** [comment]
I would suggest to duplicate the logger inside the break loop. This is a generic fix that can be applied to all the algorithms. Moving around the logger does not make sense.

**Comment by gflegar** [comment]
I did a pull request doing that, but I feel we have a different problem, and this is just a side effect of it.

The issue seems to be about what constitutes the end of an iteration. Looking at the solvers we have implemented, all of them say that the iteration is done whenever we end the while loop in the implementation. The problem is that this is completely arbitrary - a different implementation can freely move some of the operations from the end to the start of the loop or vice versa. We are not even consistent about that in the implementations we currently have:

- CG and FCG consider that the end of iteration is after the SpMV and the solution update, but before applying the preconditioner, computing the residual and checking the stopping criterion
- BICGStab and GMRES consider the iteration done after computing everything, but before checking if the stopping criterion completed
- CGS on the other hand says that the iteration is completed only once everything is done and the stopping criterion checked

We should probably figure out a reasonable point of saying what constitutes the end of an iteration, independent of the solver - otherwise, it is confusing to the user (and to us).

**Comment by hartwiganzt** [comment]
I agree. But what is the standard? Is there a standard? Is Saad's book the standard? the Matlab implementation? I agree we should be consistent across solvers, but this implies we will not have the optimal runtime for all of them. Becausethey can stop at different points. Right now all implementations are such that the earliest possible stop is used.

**Comment by gflegar** [comment]
> I agree we should be consistent across solvers, but this implies we will not have the optimal runtime for all of them. Becausethey can stop at different points. Right now all implementations are such that the earliest possible stop is used.

I don't get this. We're not talking about stopping here, we're only deciding at what point the "iteration completed" event should be emitted (which in turn has nothing to do with the organization of the loops - we can emit that event anywhere in the loop, without touching the rest of the code). Changing that does not impact the convergence or the performance of the solver in any way - it only impacts what the outside user sees.

**Comment by hartwiganzt** [comment]
Understood. Yes, you are right. There is no strict relation - except for we want to log once we have a new residual, maybe. But, I agree. We should log always in the same place. Maybe the solution update is a reasonable point?

**Comment by gflegar** [comment]
Or the convergence test?

BICGStab has 1 solution update every 2 iterations for example, GMRES has 1 solution update per restart, so it may not be the best point.

**Comment by hartwiganzt** [comment]
> Or the convergence test? BICGStab has 1 solution update every 2 iterations for example, GMRES  has 1 solution update per restart, so it may not be the best point.
Good point. Convergence test might be a better choice. But it can happen very early in the loop. So, for example, for CG, not even the SpMV is invoked at that point. Which means, we have a different iteration count than SpMV count. (Except for if we count the SpMV outside the loop)
