### ISSUE TITLE
Abstracting all used CUDA intrinsics (e.g. `__syncthreads()`) and remove depricated code

### ISSUE THREAD

**Issue by thoasm** [ginkgo-project/ginkgo#230]
Since Nvidia sometimes changes their API (like they did with the shuffles), it would be nice if all calls to such functions would be done through our own functions which mask them.

Also, we currently have a lot of depricated functions ourselves like in `cuda/components/synchronization.cuh`, which should be removed before the release (the synchronization should be done with `cuda/components/cooperative_groups.cuh`).

Examples for functions that should be abstracted (if you know more, please extend the list, as it is not complete):
- `__syncthreads()`

**Comment by gflegar** [comment]
> Also, we currently have a lot of depricated functions ourselves like in `cuda/components/synchronization.cuh`, which should be removed before the release

Just to note: this is not as straightforward as one might think. I planned doing it as soon as soon as I introduced the cooperative groups API to Ginkgo, but then realized that there's plenty of code depending on it, where it is not straightforward to replace the calls with cooperative groups. This is why I just marked the functionality deprecated, in hopes that the first person modifying the code that uses it will also figure out how to replace it with cg.

**Comment by gflegar** [comment]
As for the functions that need to be replaced. I think that intra-thread communication basically goes under the following categories:

- [Memory fence functions](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#memory-fence-functions)
- [Synchronization functions](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#synchronization-functions)
- [Warp vote functions](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#warp-vote-functions)
- [Warp match functions](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#warp-match-functions)
- [Warp shuffle functions](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#warp-shuffle-functions)
- [Warp matrix functions](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#wmma)

So any function in one of these categories should be handled by cooperative groups. Note that not all of them are supported by the current NVIDIA's implementation, nor our extensions of cooperative groups, so you should extend the functionality of the appropriate cooperative group if you need something that's not already there. Also, in case you come across any other function that requires collaboration between multiple threads to complete, this is a candidate for cooperative groups.

When it comes to designing new components in Ginkgo, whenever you create a device function that has to be called from multiple threads to succeed, it should have a cooperative group as a template parameter. You can check if the cooperative group that was passed has the required capabilities by using one of the trait class templates available with cooperative groups (or create a new trait if the capability cannot be queried using one of the existing ones).

**Comment by thoasm** [comment]
@gflegar Thank you for the detailed description!
I will take care of that as soon as I am done with the GMRES CUDA implementation (so probably starting on Monday next week).
