### ISSUE TITLE
CMake error: Unable to specify include directories for imported targets

### ISSUE THREAD

**Issue by thoasm** [ginkgo-project/ginkgo#234]
When trying to compile on my home PC (Ubuntu 18.04), I encountered the following error when performing `cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DDEVEL_TOOLS=ON -DBUILD_TESTS=ON -DBUILD_REFERENCE=ON -DBUILD_OMP=ON -DBUILD_CUDA=ON ../..` on a clean build folder:
```
CMake Error at cmake/package_helpers.cmake:68 (target_include_directories):
  Cannot specify include directories for imported target "gtest".
Call Stack (most recent call first):
  third_party/gtest/CMakeLists.txt:6 (ginkgo_add_external_target)


CMake Error at cmake/package_helpers.cmake:68 (target_include_directories):
  Cannot specify include directories for imported target "gtest_main".
Call Stack (most recent call first):
  third_party/gtest/CMakeLists.txt:8 (ginkgo_add_external_target)


CMake Error at third_party/gtest/CMakeLists.txt:10 (add_library):
  add_library cannot create ALIAS target "GTest::GTest" because target
  "gtest" is IMPORTED.


CMake Error at third_party/gtest/CMakeLists.txt:11 (add_library):
  add_library cannot create ALIAS target "GTest::Main" because target
  "gtest_main" is IMPORTED.
```
Here is the full output: [cmake_output.txt](https://github.com/ginkgo-project/ginkgo/files/2884892/cmake_output.txt)

My CMake version is `3.10.2`.

After some digging, `target_include_directories` can be used with `IMPORTED` libraries since CMake `3.11.0` (here the [MergeRequest from cmake](https://gitlab.kitware.com/cmake/cmake/merge_requests/1264)).

I think we should either change that, or, increase the required version further to `3.11`.

**Comment by thoasm** [comment]
@tcojean Do you have any ideas how to resolve it? You have a lot more knowledge and experience in CMake than I do.

**Comment by thoasm** [comment]
Unfortunately, making them `INTERFACE` did not work (I changed [line 51 of package_helpers.cmake](https://github.com/ginkgo-project/ginkgo/blob/develop/cmake/package_helpers.cmake#L51) to `add_library(${name} ${build_type} INTERFACE)`). I get the follwoing error:
```
add_library INTERFACE library specified with conflicting/multiple types.
```
Here is the full output: 
[cmake_out.txt](https://github.com/ginkgo-project/ginkgo/files/2885054/cmake_out.txt)

I guess I will play around with it a bit more and see if I can resolve it today. For the meantime, I will create the PR for GMRES (which I was trying to test after rebasing) and hope it works.

**Comment by tcojean** [comment]
Another option could be to directly set the property `INTERFACE_INCLUDE_DIRECTORIES` (https://cmake.org/cmake/help/v3.9/manual/cmake-properties.7.html) instead of using the command target_include_directories.

We would have to also drop the aliases which is annoying as we cannot use `GTest::GTest` in the namespace way, but maybe the simple `gtest` and `gtest_main` would still work both when using a pre-installed package and the imported target.

**Comment by thoasm** [comment]
Using`SET_PROPERTY(TARGET ${name} APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${${name}_INCLUDE_DIR})`
instead of `target_include_directories` and
dropping the `add_library(<namespace_name> ALIAS <name>)` (while replacing the `namespace_name` with the `name` given to the macro `ginkgo_add_external_target()`) works for not getting a CMake error.

However, when compiling, I get
```bash
make[2]: *** No rule to make target 'third_party/gflags/build/lib/./libgflags.a', needed by 'benchmark/matrix_generator/matrix_generator'.  Stop.
```
Guess I still need to add something in order for it to work.

**Comment by tcojean** [comment]
I think you should not be able to use the namespaced name in the macro `ginkgo_add_external_target`, because the namespace does not match the Ginkgo project and it does not want us to touch that.


Things to check for your problem:
+ Did you put back the targets as `IMPORTED`?
+ Is this with a clean build?

**Comment by thoasm** [comment]
> Did you put back the targets as `IMPORTED`?

Yes, I put the `IMPORTED GLOBAL` back in (also did a `git diff`, I only added the `SET_PROPERTY` and removed the `target_include_directories`)

And it was with a clean build (removed everything prior to the `cmake`).

A call to the macro looks like this at the moment: 
```
ginkgo_add_external_target(gtest_main src/googletest/include build/googlemock/gtest STATIC "d" gtest_external FALSE)
```
I replaced `GTest::Main` (and the others) in the `create_test.cmake` with `gtets_main` (and the others accordingly).
