### ISSUE TITLE
ELL conversion to Dense fails on CUDA

### ISSUE THREAD

**Issue by gflegar** [ginkgo-project/ginkgo#245]
Just started getting an error with the `Ell.ConvertToDenseIsEquivalentToRef` test. Since I was not getting it before, I guess it's accessing unset memory, or maybe a race condition somewhere.

[Here](https://github.com/ginkgo-project/ginkgo/files/2916769/errors.txt) is the output I'm getting.

It seems that the second part of `ddense_mtx` are all `-nan`s.

**Comment by tcojean** [comment]
CDash highlights the problem. There are two uninitialized errors with valgrind.
https://my.cdash.org/viewDynamicAnalysisFile.php?id=4333541
