### ISSUE TITLE
Remove `enable_language(CUDA)` when using statically installed Ginkgo with CUDA

### ISSUE THREAD

**Issue by thoasm** [ginkgo-project/ginkgo#277]
To prevent the `CMAKE_CUDA_DEVICE_LINK_EXECUTABLE` not being set error, we currently have to put `enable_language(CUDA)` in the CMake file when using a statically build, installed version of Ginkgo. However, there is another way:
When looking at the file `${CMAKE_INSTALL_PREFIX}/lib/cmake/Ginkgo/GinkgoTargets.cmake`, there is a line:
```cmake
IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CUDA;CXX"
```
which is probably slightly altered when building in release mode. When we change that line to:
```cmake
IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
```
We no longer get the error about `CMAKE_CUDA_DEVICE_LINK_EXECUTABLE`, and we are still able to use the CUDA part of Ginkgo. This is also mentioned in our 
[known issues](https://github.com/ginkgo-project/ginkgo/wiki/Known-Issues).

We could automate this process, so the user no longer needs the `enable_language(CUDA)` when he build Ginkgo as a static library with CUDA.

This work-around is taken from the [open issue from CMake](https://gitlab.kitware.com/cmake/cmake/merge_requests/2704) about this exact problem, and tested on the CI server.

**Comment by tcojean** [comment]
That is probably because we are using `target_link_libraries(ginkgo PUBLIC ginkgo_cuda [...])`. Maybe using `PRIVATE` linking does not add the CUDA language as you just found out, and would also maybe not create problem for the users (the Ginkgo core module is the only one they should have to know about, probably).

**Comment by thoasm** [comment]
Good point, I will test this.

**Comment by thoasm** [comment]
Unfortunately, linking to `ginkgo_cuda` as `PRIVATE` does not resolve this issue (I made every linking containing one of the 4 ginkgo libraries `PRIVATE`).

**Comment by tcojean** [comment]
I'm not sure if we can call this fixing, but the recent #553 did something in that direction: the `enable_language(CUDA)` is now done automatically whenever we use a static build.

Technically, I don't think there is any way around this issue: if Ginkgo was built statically, that means all the things it depends on cannot be bundled/linked to Ginkgo, so it needs to be propagated to one level up (where Ginkgo will be linked to, either executable or library). All we can do is help the users as #553 does, I think.
