### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by tcojean** [ginkgo-project/ginkgo#281]
### Visual Studio related problems
A potential issue are the compiler differences between Visual Studio and G++/Clang. It is possible that Ginkgo requires some bug fixes for proper Visual Studio support.

### Shared library building
A known issue is that build fails on Windows due to missing shared libraries.

Seems that this stackoverflow question is related: https://stackoverflow.com/questions/33062728/cmake-link-shared-library-on-windows

It seems there is this generate_export_header command in CMake, which has to be done for every shared library we create, and the source code should be modified accordingly: https://cmake.org/cmake/help/v3.9/module/GenerateExportHeader.html

Some resources related to this:
+ https://msdn.microsoft.com/en-us/library/ms235636.aspx
+ http://dominoc925.blogspot.de/2016/08/use-cmake-to-help-build-and-use-windows.html

**Comment by yhmtsai** [comment]
Windows has the following options to compile C++ program.
1. Windows Subsystem for Linux (WSL)
-- The compilation is not different from ubuntu.
-- WSL 2 may support GPU access in the future. (But they set GPU access as the highest priority about two years ago)
2. MinGW
It can be used by `cmd` or `powershell`. However, CUDA can not be compiled by MinGW.
3. Cygwin
it depends on the installation of gcc.
3. Visual Studio
-- The only one supports CUDA compilation in Windows.

I tried to see how to compile ginkgo static library in Visual Studio without CUDA.
I record the problem and how I solve it.
1. it can not recognize the overloaded template with enable_if correctly.
For example, 
```
template <typename T>
        static xstd::enable_if_t<is_complex<T>()> write_entry_impl(
            std::ostream &, const T &) {}
template <typename T>
        static xstd::enable_if_t<!is_complex<T>()> write_entry_impl(
            std::ostream &, const T &) {}
```
The compiler complain that the functions are redefined.
It can works with set the second template argument as `template <typename T, int = 0>`
The workaround solution can use [this](https://stackoverflow.com/questions/28203981/is-the-lazy-mans-enable-if-legal-c), to add one specified key.

2. `isfinite` is defined without any namespace, so the possible solution is similar to clang compiler.
I only rename it in my try.
3. In `core/test/stream` the output `1234abcd` -> `00001234abcd` are different. the default string format might be different.
e.g. Use `ptrstream << std::hex << "0x" << reinterpret_cast<gko::uintptr>(&dummy);` to ensure the same format [here](https://github.com/ginkgo-project/ginkgo/blob/7c1edc49e27225201ce69499fae5be66f2aa66a3/core/test/log/stream.cpp#L77)
4. Compiler can not find the correct function for [clone(LinOp *)](https://github.com/ginkgo-project/ginkgo/blob/1b9b919d566cab75cee6291f3adf16cd922f06fb/core/base/combination.cpp#L80). The line should use `x->clone()` not `clone(x)`

After doing these fixes, Visual Studio can compile ginkgo static library without CUDA.

**Comment by tcojean** [comment]
I am tentatively adding this to the v1.1.0 milestone as we have pretty much everything for this (except for merging @yhmtsai #351 PR). If this still needs a lot of stabilization and is not ready, this can be removed.  We should at least have partial windows support (MinGW was merged and we are hopefully still compatible).

**Comment by yhmtsai** [comment]
For the MSVC unrecognized SFINAE, use constexpr member of struct not constexpr function.
original version:
```C
template <typename T>
        static xstd::enable_if_t<is_complex<T>()> write_entry_impl(
            std::ostream &, const T &) {}
template <typename T>
        static xstd::enable_if_t<!is_complex<T>()> write_entry_impl(
            std::ostream &, const T &) {}
```
Fixed version
```C
template <typename T>
        static xstd::enable_if_t<is_complex_s<T>::value> write_entry_impl(
            std::ostream &, const T &) {}
template <typename T>
        static xstd::enable_if_t<!is_complex_s<T>::value> write_entry_impl(
            std::ostream &, const T &) {}
```

For exporting shared library, set `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE` to let cmake automatically export the symbols.

**Comment by tcojean** [comment]
We now have full windows support, so I will close this although it is still a good reference to point people to.
