### ISSUE TITLE
Monotonic and Adjustable Clocks

### ISSUE THREAD

**Issue by keldu** [ginkgo-project/ginkgo#293]
I saw at least in some tests the use of std::chrono::system_clock which is not guaranteed to be a monotonic, non-adjustable clock on all systems, so it could be changed during runtime which can result in wrong results/tests.

https://github.com/ginkgo-project/ginkgo/blob/develop/reference/test/stop/combined.cpp

https://en.cppreference.com/w/cpp/chrono/system_clock

If the purpose is to measure time intervals you should always use 

https://en.cppreference.com/w/cpp/chrono/steady_clock

since it guarantees a monotonic none changing clock.

**Comment by keldu** [comment]
https://github.com/ginkgo-project/ginkgo/search?q=std%3A%3Asystem_clock&unscoped_q=std%3A%3Asystem_clock

Just a small search for 'std::system_clock' in the project

**Comment by keldu** [comment]
The most important thing is that std::chrono::system_clock is adjustable which can result in negative runtimes and std::chrono::steady_clock is not.

**Comment by pratikvn** [comment]
@keldu , Thanks for creating this issue. Good find. If you want to go ahead and create a pull request, feel free to do so. Replacing all instances of `std::chrono::system_clock` by `std::chrono::steady_clock` project wide should do the job (We only seem to use `now` and `time_point` which should be available in both.)

You can create a fork and create a branch on your fork, make these changes and create a pull request to merge the branch from your fork to ginkgo's develop. Also, please remember to add yourself to the contributor's list if you do this.

**Comment by tcojean** [comment]
Simply as a precision, I do think this is a slight problem but not such a big deal.

The only practical case where `system_clock` is non steady is when the user adjusts the time manually during a benchmark. If he does that, then that's a naughty user. In the end `steady_clock` (or `high_resolution_clock`?) are more suited for benchmarking purpose, but it's not a requirement for the release as the problem sits in corner cases.

I'm not even sure that daylight change would create a problem actually... I need to look more into this one.

**Comment by keldu** [comment]
I'm more worried about wrong ntp updates and not users breaking things.

If the the wall/system_clock time is based directly on the hardware clock, then most of the times linux users shouldn't be affected by daylight saving changes, since the hardware clock is normally set to UTC. Windows writes its local timezone per default into the hw clock, so that's a different story.

I agree that it's not critical.

high_resolution_clock is in gcc just a typedef of system_clock. It can also be a typedef of steady_clock on other compilers. Or a third independent one.

**Comment by tcojean** [comment]
I'm not really certain `ntp` would update time in such a big quantity that it is practically noticable for our benchmarks, but yes it could happen.

Anyway, I will integrate this as part of #292 as this provides easy integration. Thanks for the issue.
