### ISSUE TITLE
Add full ParILU OpenMP support

### ISSUE THREAD

**Issue by thoasm** [ginkgo-project/ginkgo#321]
I just realized that in order to fully support ParILU with OpenMP, we need the kernel `omp::sort_by_column_index` if the matrix was not sorted previously. Now, it throws a `NOT_IMPLEMENTED` exception if the matrix should be sorted by the ParILU.

**Comment by hartwiganzt** [comment]
True. It is OK for now, but we need to keep it in mind..

**Comment by thoasm** [comment]
I will take care of this.
I already wrote parts of it in the branch [`extend_parilu_omp`](https://github.com/ginkgo-project/ginkgo/tree/extend_parilu_omp), and will create a PR as soon as I am done.
