### ISSUE TITLE
omp/test/factorization/par_ilu_kernels FAILS

### ISSUE THREAD

**Issue by cayrols** [ginkgo-project/ginkgo#329]
Hi,

We got a failed running test when doing 'make test' :

The following tests FAILED:
	 88 - omp/test/factorization/par_ilu_kernels (Failed)

The output of the execution is the following 

> [==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from ParIlu
[ RUN      ] ParIlu.OmpKernelInitializeRowPtrsLUEquivalentToRef
/home/scayrols/Sources/ginkgo/omp/test/factorization/par_ilu_kernels.cpp:78: Failure
Failed
Could not find the file "ani1.mtx".
Please make sure you call this test from the directory where this binary is located, so the matrix file can be found.
[  FAILED  ] ParIlu.OmpKernelInitializeRowPtrsLUEquivalentToRef (1 ms)
[ RUN      ] ParIlu.KernelInitializeParILUIsEquivalentToRef
/home/scayrols/Sources/ginkgo/omp/test/factorization/par_ilu_kernels.cpp:78: Failure
Failed

Cheers,
Sébastien

**Comment by thoasm** [comment]
Hi Sébastien,

thank you for your input and interest in Ginkgo.
Is it possible that you compiled an older version of Ginkgo? If I recall correctly, the error should now read something like this:
`Could not find the file "/absolute/path/to/ani1.mtx", which is required for this test.`

**Comment by cayrols** [comment]
Thomas,

Sorry about that !
You were right, I did not have the latest version.
I just pull and recompile, and the tests went well.

Thanks you and, again, sorry about that.

Sébastien

**Comment by thoasm** [comment]
Don't worry, that happens.
