### ISSUE TITLE
How to support multiple variants of TRS (triangular solvers)

### ISSUE THREAD

**Issue by thoasm** [ginkgo-project/ginkgo#333]
@pratikvn and I were discussing how to support the multiple versions of triangular solvers:
- lower triangular solver (taking the L matrix)
- upper triangular solver (taking the U matrix)
- full triangular solver (taking both L and U).
  This is definitively up for discussion if we should bundle it with the others, or make it a dedicated solver.

Currently, we thought about two options on how to support it:
1. Having a single TRS class which must be created with a parameter which decides on what solving step is necessary. This is an example code how the user interface would look like: 
```c++
// For solving both L and U at the same time
auto full_conf = Trs::config::full;
auto full_trs_factory = Trs<>::build().with_config(full_conf).on(exec);
auto full_trs_solver = full_trs_factory->generate(lu_factors);

// For just solving according to L
auto l_conf = Trs::config::lower;
auto l_trs_factory = Trs<>::build().with_config(l_conf).on(exec);
auto l_trs_solver = l_trs_factory->generate(l_factor);
   ```
2. Having separate solvers for all three versions (could be implemented as an adapter / wrapper of one class which does all, to reduce code duplication). Code example of the user interface:
```c++
// For solving both L and U at the same time
auto full_trs_factory = FullTrs<>::build().on(exec);
auto trs_solver = full_trs_factory->generate(lu_factors);

// For just solving according to L
auto l_trs_factory = LowerTrs<>::build().on(exec);
auto l_trs_solver = l_trs_factory->generate(l_factor);
```

The names I have chosen are probably not ideal and can be changed, I just did not come up with a better naming scheme at the time of writing. So please don't reject one proposal just because the name sounds weird / wrong.

I think we should decide on a path before merging PR #327, so we can directly implement it there before merging.

**Comment by pratikvn** [comment]
If we do not want to rely on enums and for the user to worry about looking up the parameters in the documentation then I guess we should go with the second option, but personally I do not mind the first option as that seems intuitive to me.

**Comment by thoasm** [comment]
Personally, I prefer the 2nd option.

The 1st option probably has less code duplication, however, for the 2nd option:
+ We do not have to expose any enum (or similar) to the user, and a `with_config` (or similar) would not be necessary
+ The name of the class represents directly what it does, so less confusion for the user, while also directly stating what matrix should be given in the `generate` step

All in all, the user does not need to read the documentation too thorough to understand the usage.

But I am happy for any input.

**Comment by hartwiganzt** [comment]
What we should consider: how would it look like if we use a CG as triangular solver? For the second option, I assume it would be:
```c++
// For just solving according to L
auto l_cg_factory = Cg<>::build().on(exec);
auto l_cg_solver = l_cg_factory->generate(l_factor);
```

**Comment by thoasm** [comment]
Well, if you want to use CG for either a lower or an upper triangular solver, you just create a CG solver and give it the matrix, so your first example is correct (would not change if we would go with option 1 or 2).
For a full triangular solve, we did not consider the option to change the solver yet, so both versions would not work. If we want to have that, we would need to make the full triangular solver a separate solver and do something similar to what I do with the LU preconditioner (making the L and U sovler type a template parameter).

**Comment by hartwiganzt** [comment]
So with option 2, we could do 
```c++
// For solving L
auto l_cg_factory = Cg<>::build().on(exec);
auto l_cg_solver = l_cg_factory->generate(l_factor);
// For solving U
auto u_bicgstab_factory = Bicgstab<>::build().on(exec);
auto u_bicgstab_solver = l_bicgstab_factory->generate(u_factor);
```

**Comment by pratikvn** [comment]
@hartwiganzt yes, that would work with both option 1 or 2.

**Comment by thoasm** [comment]
@hartwiganzt The question here is more how we should handle a specific solver for Lower Triangular matrices and for Upper Triangular matrices:
Should both be integrated into the same class, or separate ones?

What you ask for (and how it is currently handled in the branch) would be:
```c++
auto ilu_precond_factory = AbstractIlu<Cg<>, Bicgstab<>>::build().on(exec);
auto ilu_precond = ilu_precond_factory->generate(l_u_factors);
```

This is still not final, but how it currently works. It uses Cg as the L-solver, and Bicgstab as the U-solver in the given example.

**Comment by hartwiganzt** [comment]
Looks good, I think!

**Comment by pratikvn** [comment]
I guess based on the consensus, we should go with the separate classes implementation.I see the following steps:
1. For #327 , I will rename it to LowerTrs as it does the lower triangular solve and keep everything else same for now.
2. After merging #327, the next PR would be for the CUDA kernels, which are also done. See the [trs-cuda-kernels](https://github.com/ginkgo-project/ginkgo/tree/trs-cuda-kernels) branch.
3. After this we can create an adapter/base TRS class and create three sub-classes, LowerTrs, UpperTrs and FullTrs. Only the implementation in the core would change as the kernels should essentially remain the the same, so hopefully it should be easier to review and implement.

The reason that I dont want to do in PR #327 is because, I think that could get messy and difficult to review. But if anyone else wants me to do it in that PR itself, I am happy to be convinced.

**Comment by thoasm** [comment]
(I forgot to comment on that when I read it:) I am perfectly fine with that.
You might decide to make an abstract / general class to support both lower and upper solves to reduce the code duplication, but that is also fine to do in a separate PR (or not at all). Maybe it is also useless, I guess you will see when you implement the upper TRS.

**Comment by tcojean** [comment]
Since this was merged, I think this can be closed. Feel free to reopen if more discussion is needed.
