### ISSUE TITLE
The name of (I + coef * U * V)

### ISSUE THREAD

**Issue by yhmtsai** [ginkgo-project/ginkgo#335]
Currently, I use 'Reflection' for the operator (I + coef * U * V) in the PR #334 
@pratikvn suggests that using Perturbation is better.
Pertubation is a operation for (I + X), X is coef * U * V here.

I conclude the discussion with @pratikvn here.
1. Reflection: the operator does not only reflection but projection.
2. Update: Cuda uses rank-1 update or rank-k update on the matrix, but LinOp not only apply to a matrix.
3. Transformer: too general

**Comment by pratikvn** [comment]
If you expand it, the perturbation should look like `X + \epslion`. The operator above when applied to a vector(matrix) would look like ` Op = (I + coef * U*V )`

and `Op * x = (I + coef * U*V ) x = x +  coef * U*V*x ` which can be seen as `x + \epsilon`, so I think perturbation is a better fit. 

Reflection is a special part when `coef = -1` and `V = U^T`

**Comment by yhmtsai** [comment]
I use Perturbation first.
If someone has any idea about the name, I can change it again.

**Comment by pratikvn** [comment]
See PR #334
