### ISSUE TITLE
coo matrix performance with OpenMP

### ISSUE THREAD

**Issue by nbeams** [ginkgo-project/ginkgo#339]
With only one (or maybe a small number of? My test was for one) right hand side(s) to solve for, the coo matrix format sees significant slowdown when using OpenMP executor, for the same code where a csr matrix gets the expected speedup.

**Comment by thoasm** [comment]
Thank you for catching that problem.

I did some tests, and this behavior is definitively reproducible. I ran a timed SpMV (by modifying the test of COO) with a matrix size of `5320 x 2310`. I got the following results when compiling in release mode (run on my Laptop):
```
Duration ref [us]: 23531
Duration omp [us]: 11639820
```

It looks like the the parallel for in the COO `apply` goes over the number of right hand sides, which might be faster for multiple right hand sides, but is definitively slower for just one.
