### ISSUE TITLE
Is the third-party library installed by ginkgo a system or local third-party library?

### ISSUE THREAD

**Issue by yhmtsai** [ginkgo-project/ginkgo#343]
In [Contributing guideline](https://github.com/ginkgo-project/ginkgo/wiki/Contributing-guidelines#include-statement-grouping), we split the third-party library to system and local library.
Is the third-party libraries like gtest, rapidjson, and gflags which are installed by ginkgo the system or local libraries?
1. if they are local third-party library, they should be `#include "third-party"` not `#include <third party>` in the repo.
2. if they are system third-party library, everything is fine.

**Comment by thoasm** [comment]
I agree that it probably should be `#include "gtest/gtest.h"` since it is not part of the headers we export / install / give the user (therefore, I would consider it a local third-party library).

**Comment by tcojean** [comment]
They can be a non-local third party library, since we support  using pre-installed GTest.

See [the INSTALL.md file](https://github.com/ginkgo-project/ginkgo/blob/develop/INSTALL.md#third-party-libraries-and-packages)

**Comment by thoasm** [comment]
Ah, good to know, thanks!
So I guess since both cases could apply, I would go with the system third-party approach (partly since we write it like that everywhere up until now).

**Comment by yhmtsai** [comment]
Got it. thanks.
