### ISSUE TITLE
Documentation PDF build issue

### ISSUE THREAD

**Issue by tcojean** [ginkgo-project/ginkgo#356]
As can be seen from the [latest failing pipeline](https://gitlab.com/ginkgo-project/ginkgo-public-ci/pipelines/85536967), we have a problem building the PDF version of the documentation. I have thoroughly investigated this issue, but still could not come up with a proper solution, although there are multiple potential ways to solve this problem. 

In general, the actual error that we get is the following:
```
! pdfTeX error (ext4): \pdfendlink ended up in different nesting level than \pdfstartlink.
\AtBegShi@Output ...ipout \box \AtBeginShipoutBox
                                                  \fi \fi
l.10 {\ttfamily \#
                  include $<$ginkgo/core/matrix/coo.\+hpp$>$}

```

This error roughly means the following: the latex processor has internal sanity check rules stating that a small text box of some type, usually what a link is wrapped into, cannot span on multiple pages (in general, have varying nesting levels). Whenever this happens, the latex processor throws this error and aborts PDF generation. AFAIK this isn't tied to some PDF formatting rules (as in, links should only be on one page) but rather something the PDF generation step imposes itself. This issue in general seems to arise often on the net, most of the time when the link is in a weird environment which has this sort of issue happening often (articles two column are/were an issue for a long time, it was fixed in some later version thanks to some workaround). Examples of this issue:
+ https://tex.stackexchange.com/questions/1522/pdfendlink-ended-up-in-different-nesting-level-than-pdfstartlink
+  https://tex.stackexchange.com/questions/63819/mysterious-error-pdfendlink-ended-up-in-different-nesting-level-than-pdfstart?noredirect=1&lq=1 (also explains mbox)
+ https://tex.stackexchange.com/questions/249579/pdfendlink-ended-up-in-different-nesting-level-than-pdfstartlink-error-with/249743#249743 (twocolumn ""fix"")

The error here seems to be reported for COO, although with investigation this happens in the previous item on the list, namely this file:
```
\input{classgko_1_1ConvertibleTo}
```

What we see there, or when we look into the [last generated pdf](https://ginkgo-project.github.io/ginkgo/doc/pdf/develop.pdf), page 249, we have a long list of hyperlinks which are links towards classes implementing this interface (ConvertibleTo), which is pretty much everything in Ginkgo. Luck has it that @thoasm 's recent commit added an extra long line in the file, which ends up being cut on two pages and throws this error. Commenting all the backlink blocks from this file allows to properly generate the documentation afterwards.

### The fixes
1. On my system (debian), I was able to upgrade to some [experimentally provided doxygen 1.8.16 version](https://packages.debian.org/experimental/doxygen) where they do ""fix"" that issue with the backlink, by wrapping every single one of them into a `\mbox{}`, like so:
```latex
\mbox{\hyperlink{classgko_1_1EnablePolymorphicAssignment_a6b7e6872e96084636f8ab5091063ada8}{gko\+::\+Enable\+Polymorphic\+Assignment$<$ Ilu$<$ L\+Solver\+Type, U\+Solver\+Type, Reverse\+Apply $>$ $>$}}
```
From my understanding, the mbox is a way to tell text to stay on one line and never have a linebreak. This is BTW a poor man's fix, as now all the links tend to go way outside of the margins of the pdf document. The problem is getting a proper doxygen 1.8.16 on our containers for ubuntu (18.04 and 16.04). I tried manual installation and that seems not complete enough for our PDF generation. As a side note, upgrading the texlive suite also doesn't help here.

2. Other ways to fix this issue for all doxygen versions would be to disable either the backlink feature (could not find how to do it yet) or the hyperlinks altogether (easy but the PDF becomes impractical).

I welcome any contribution on this topic, particularly if anyone is able to have a working doxygen 1.8.16 on ubuntu 16.04 and/or 18.04.

**Comment by yhmtsai** [comment]
I only try using doxygen 1.8.16 on Ubuntu 16.04.
CMake uses `-DGINKGO_BUILD_DOC=ON -DGINKGO_DOC_GENERATE_EXAMPLES=ON -DGINKGO_DOC_GENERATE_PDF=ON -DGINKGO_BUILD_CUDA=ON -DGINKGO_DEVEL_TOOLS=OFF`
I do not see any error but some warnings.
<details>
<summary>warning</summary>
<pre><code>
warning: Tag 'PERL_PATH' at line 83 of file '/home/u/mike/kit/review/ginkgo/build/doc/Doxyfile-pdf' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: source /home/u/mike/kit/review/ginkgo/doc/images/ is not a readable file or directory... skipping.
/home/u/mike/kit/review/ginkgo/include/ginkgo/core/matrix/dense.hpp:515: warning: Member initialize found in multiple @ingroup groups! The member will be put in group mat_formats, and not in group LinOp
/home/u/mike/kit/review/ginkgo/include/ginkgo/core/matrix/dense.hpp:554: warning: Member initialize found in multiple @ingroup groups! The member will be put in group mat_formats, and not in group LinOp
/home/u/mike/kit/review/ginkgo/include/ginkgo/core/matrix/dense.hpp:585: warning: Member initialize found in multiple @ingroup groups! The member will be put in group mat_formats, and not in group LinOp
/home/u/mike/kit/review/ginkgo/include/ginkgo/core/matrix/dense.hpp:634: warning: Member initialize found in multiple @ingroup groups! The member will be put in group mat_formats, and not in group LinOp
Generating pdf PDF from LaTeX
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./refman.tex
LaTeX2e <2018-12-01>

This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning input file refman.idx....done (867 entries accepted, 0 rejected).
Sorting entries..........done (9343 comparisons).
Generating output file refman.ind....done (1202 lines written, 0 warnings).
Output written in refman.ind.
Transcript written in refman.ilg.
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./refman.tex
LaTeX2e <2018-12-01>

Package longtable Warning: Table widths have changed. Rerun LaTeX.
Rerunning latex....
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./refman.tex
LaTeX2e <2018-12-01>

This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning input file refman.idx....done (867 entries accepted, 0 rejected).
Sorting entries..........done (9343 comparisons).
Generating output file refman.ind....done (1202 lines written, 0 warnings).
Output written in refman.ind.
Transcript written in refman.ilg.
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./refman.tex
LaTeX2e <2018-12-01>

[ 99%] Built target pdf
[100%] Generating usr documentation with Doxygen
warning: Tag 'PERL_PATH' at line 83 of file '/home/u/mike/kit/review/ginkgo/build/doc/Doxyfile-usr' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
[100%] Built target usr
</code></pre>
</details>
Do I also need to turn `GINKGO_DOC_GENERATE_DEV` on?

**Comment by tcojean** [comment]
@yhmtsai no, this is the settig that should generate the error.

How did you install doxygen 1.8.16 and texlive 2019 on ubuntu 16.04?

**Comment by yhmtsai** [comment]
I take their 1.8.16 release from [doxygen github](https://github.com/doxygen/doxygen)
Change cmake PREFIX to my local folder.
texlive: I use the script from [link](https://www.tug.org/texlive/acquire-netinstall.html)
Also, install Graphviz (dot) from [SourcePackage](https://graphviz.gitlab.io/_pages/Download/Download_source.html) into my local folder.

**Comment by tcojean** [comment]
OK thanks. That's pretty much exactly what I tried with the containers earlier and that did not work. I will have to try some more I guess.

**Comment by yhmtsai** [comment]
You have root access in container, so you maybe can use yum/apt install to do the similar things.
I am not sure whether texlive adds or modifies files during building document.
If texlive does not change anything, installing it out of container and mounting the folder maybe works.

**Comment by yhmtsai** [comment]
Yes, the link are out of the page.
<img width="841" alt="image" src="https://user-images.githubusercontent.com/19565938/66237949-9d7bf280-e6f6-11e9-894c-40b935d5aa36.png">

**Comment by hartwiganzt** [comment]
I understand correctly, that the hyperlink exceeds what can be printed on a page, and therefore breaks the pdf?

**Comment by tcojean** [comment]
@hartwiganzt it's rather that luck has it that one link out of that big link block ends up being half on one page and half on another page, which breaks the PDF generation step.

**Comment by hartwiganzt** [comment]
So a \newpage would resolve the issue (in an ugly way, however...)

**Comment by tcojean** [comment]
The problem is all of this is automatically generated by doxygen. That would fix the issue but knowing where to put this is another idea.
As we were discussing with Mike, it looks like upgrading both texlive and doxygen to bleeding edge versions work. But if we go that direction Ginkgo's documentation would require bleeding edge related software.
