### ISSUE TITLE
Compilation Issue on MacOS

### ISSUE THREAD

**Issue by hartwiganzt** [ginkgo-project/ginkgo#383]
I have problems compiling the OMP version on MacOS:
>>>
[ 16%] Linking CXX shared library libginkgo_omp.dylib
Undefined symbols for architecture x86_64:
  "gko::OmpExecutor::raw_copy_to(gko::HipExecutor const*, unsigned long, void const*, void*) const", referenced from:
      vtable for gko::OmpExecutor in executor.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [omp/libginkgo_omp.dylib] Error 1
make[1]: *** [omp/CMakeFiles/ginkgo_omp.dir/all] Error 2
<<<

the complete CMake cache attached.
[CMakeCache.txt](https://github.com/ginkgo-project/ginkgo/files/3848777/CMakeCache.txt)

[CMakeOutput.log](https://github.com/ginkgo-project/ginkgo/files/3848786/CMakeOutput.log)
[CMakeError.log](https://github.com/ginkgo-project/ginkgo/files/3848787/CMakeError.log)

**Comment by yhmtsai** [comment]
It is also failed on my MacOS
