### ISSUE TITLE
format #include header

### ISSUE THREAD

**Issue by yhmtsai** [ginkgo-project/ginkgo#389]
I would like to add a script to format the sorting of header at https://github.com/ginkgo-project/ginkgo/tree/update_header.
It can also handle the "hip/hip_runtime.h" and the usage of "" or <>.

I tried to set some rules to following the code and contributing guide
Except the main header, others are sorted by clang-format whose version is larger than 6

For the main header, the rule of this script is:
1. all executor files use #include <ginkgo/core/base/executor.hpp>
2. get the possible name from the headers in `include/ginkgo/core` and `core/test/utils` (for assertions or matrix_generator)
3. try to find the name which has minimal distance by the length of include. (make sure cgs not to use cg)
4. get possible header of self
5. Get all header satisfying the rules and pick the headers with the highest score.
The score is
- 300: SELF
- 250: #include <ginkgo/***> in core or test folder
- 200: #include "***kernels" not in core
- others: use length

The following are the changes:
[core](https://github.com/ginkgo-project/ginkgo/commit/cdcb2d3ac510d0727ce7aa4d82aec47a1aa774ea)
[reference](https://github.com/ginkgo-project/ginkgo/commit/a6ce5c53973589717d7e67ae37c67299f68f4351)
[cuda](https://github.com/ginkgo-project/ginkgo/commit/35193d3a29aeb17db5a05df621e9d125ab7484e0)
[omp](https://github.com/ginkgo-project/ginkgo/commit/7bc820aea0a9b3e5431af6987c586d7754b995d4)
[hip](https://github.com/ginkgo-project/ginkgo/commit/6e89f3eb29adaa0be6c95086e0566f7ef8bcdf52)

if there is a #if around #include without any newline, it may need to change it manually.
For example, [reference/test/stop/time.cpp](https://github.com/ginkgo-project/ginkgo/blob/a6ce5c53973589717d7e67ae37c67299f68f4351/reference/test/stop/time.cpp#L41).

Should we set a fixed rule to find the main header not by the score?

**Comment by upsj** [comment]
Can't `clang-format` do that already? See [IncludeCategories](https://releases.llvm.org/6.0.1/tools/clang/docs/ClangFormatStyleOptions.html)

**Comment by yhmtsai** [comment]
This is done by #447 .
See detail in #447
