### ISSUE TITLE
`examples/simple_solver.cpp` wrong name of the input file for the starting approximation

### ISSUE THREAD

**Issue by venovako** [ginkgo-project/ginkgo#39]
In `examples/simple_solver.cpp`, should
```c++
auto x = gko::read<vec>("data/x.mtx", exec);
```
be instead
```c++
auto x = gko::read<vec>("data/x0.mtx", exec);
```
since in `data` subdirectory there is `x0.mtx` but not `x.mtx`?

**Comment by gflegar** [comment]
@hartwiganzt you mind fixing this? Thanks.

**Comment by gflegar** [comment]
Also @venovako if you already have a fix ready somewhere, feel free to do a PR.
