### ISSUE TITLE
Test GPU kernels for problems larger than one thread block

### ISSUE THREAD

**Issue by hartwiganzt** [ginkgo-project/ginkgo#41]
We need to check the functionality of all GPU kernels also for problems where more than one single thread block is launched.

**Comment by gflegar** [comment]
Don't we already do that?

**Comment by hartwiganzt** [comment]
Not all tests. E.g. not for the solver kernels, and I am also not sure about whether all others do.

**Comment by gflegar** [comment]
Yes, I checked and verified there is a problem. I can tell you that all code that I wrote should have tests large enough to check this.

**Comment by gflegar** [comment]
The best we can do is check existing tests if they do that, and write a guide on how to write unit tests, and point people to it.

**Comment by tcojean** [comment]
Actually isn't it also a good thing to check for input less than `default_block_size`? So that we know if the GPU kernels support this (it should be solved with one if, but who knows).

**Comment by hartwiganzt** [comment]
I created a pull request #43 to fix this bug.

**Comment by tcojean** [comment]
I guess this can now be closed.
