### ISSUE TITLE
Building Ginkgo with HIP fails when the build path contains spaces

### ISSUE THREAD

**Issue by upsj** [ginkgo-project/ginkgo#454]
Even though this is a pathological case, we might want to avoid it.
Same issues might hold if any internally used paths contain spaces.

Can be reproduced via 

```
> mkdir "b uild" && cd "b uild" && cmake .. && make -j20
...
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
...
```

My guess would be that this has to do with unquoted strings in CMake variables

**Comment by yhmtsai** [comment]
It seems to be hipcc related problem not cmake.
I get the following commands from `make VERBOSE=1`
```
/opt/rocm/hip/bin/hipcc -M /home/ginkgo/hip/stop/residual_norm_reduction_kernels.hip.cpp -o "/home/ginkgo/b uild/hip/CMakeFiles/ginkgo_hip.dir/stop/ginkgo_hip_generated_residual_norm_reduction_kernels.hip.cpp.o.depend.pre" -std=c++11 --generate-code=arch=compute_35,code=sm_35 --expt-relaxed-constexpr -ccbin=/usr/bin/c++ --shared -Xcompiler '-fPIC' -O3 -DNDEBUG "-I/usr/include -I/opt/rocm/hipblas/include -I/opt/rocm/hipsparse/include -I/home/ginkgo/b uild/include -I/home/ginkgo/include -I/home/ginkgo -I/opt/rocm/include -I/opt/rocm/include -I/opt/rocm/include -I/opt/rocm/include"
```
the path is already in the quote

**Comment by tcojean** [comment]
You probably need to use "\"<path>\"" or something in that order.
hipcc is a bash script which will consume one level of quotes. Maybe you need even more levels it depends if there is another level of scripts being called...

**Comment by upsj** [comment]
Thanks for the investigation, @yhmtsai ! I guess it doesn't make sense to leave this issue open, then.
