### ISSUE TITLE
Not testing Papi in test_install

### ISSUE THREAD

**Issue by pratikvn** [ginkgo-project/ginkgo#458]
I think there is a small bug/typo with the test_install in that we call `gko::log::Convergence<>` twice. 

One of them should be `gko::log::Papi` in both the [`test_install.cpp`](https://github.com/ginkgo-project/ginkgo/blob/develop/test_install/test_install.cpp#L199) and the [`test_install_cuda.cu`](https://github.com/ginkgo-project/ginkgo/blob/develop/test_install/test_install_cuda.cu#L203) files.

Can someone confirm this before I create a PR ?

**Comment by tcojean** [comment]
I think that's true. You can try adding it but I'm not sure yet if it will work out of the box.

**Comment by pratikvn** [comment]
Thanks. I will see if I find some time to fix it. Probably not very high priority anyway.
