### ISSUE TITLE
Should num_stored_elements be removed from `LinOp` interface?

### ISSUE THREAD

**Issue by gflegar** [ginkgo-project/ginkgo#47]
I've been redesigning some of Ginkgo's core classes, and one thing that I'm not sure about is whether we want to expose the `num_stored_elements` property in the `LinOp` interface. We currently do that, but I think that's just for historical reasons (while we still didn't have a unified interface for all linear operators). I think that we should have this (or equivalent) parameter only in classes where it makes sense (like matrices, and some preconditioners).

The cons of having it in the base class are:

1.  It's more complicated to call the base constructor from constructors of concrete `LinOp`s, as we have to pass this extra parameter.
2.  The mathematical concept of a linear operator does not have a property "number of stored elements", so in a lot of cases we just have to make something up (and pay the price of storing it, but that's a minor concern here). E.g. what's the number of stored elements of  a linear operator `(A^+) A + (A^T) A` (`A^+` is the moore-penrose inverse), which is implemented by just keeping a reference to `A`, and computing the required operations (multiplication, transposed multiplication, solving a under/overdetermined system on the fly)? We can immediately say that the number of rows and column of such an operator is the same as the number of rows of `A`, but we cannot really say what is the number of stored elements (0, the same as that of `A`, something else?).

The only pro I can see is that users can get the number of stored elements even without knowing the type of the operator they have. However, is this a realistic use case? Can they do anything useful with such an information, even though they have no idea if they have a solver, a preconditioner, or a matrix, and which kind it is?

@ginkgo-project/developers what do you think?

I would like to include the conclusions of this discussion into #46, as I've already changes the way we handle operator sizes there, so makes no sense in changing it twice.

**Comment by hartwiganzt** [comment]
I don't have any additional comments, I agree with @gflegar .

**Comment by pratikvn** [comment]
Yes, I too agree with @gflegar . Additionally I think we should document which ones have the `num_stored_elements` and why, in the wiki or so. Maybe for all properties which are specific to one linear operator and not to others. That would make it easier to understand and use.

**Comment by tcojean** [comment]
I agree with @gflegar and @pratikvn. We should use this variable only when actually needed and document its use when needed.

**Comment by hartwiganzt** [comment]
I guess this can be closed, then.
