### ISSUE TITLE
Paper for the Journal of Open Source Software

### ISSUE THREAD

**Issue by pratikvn** [ginkgo-project/ginkgo#478]
The Journal of Open Source Software is a journal where we can publish Ginkgo so that we can cite papers that use Ginkgo easily and clearly. Some Open Source softwares that have been published can be looked at on [the JOSS webpage](https://joss.theoj.org/).

In this regard, to submit a paper there, a [joss-paper branch](https://github.com/ginkgo-project/ginkgo/tree/joss-paper) has been created. Their requirement is to have a `paper.md` and a `paper.bib` file which is in our `doc/joss` folder. 

In general, the idea is to have a small summary of the features of Ginkgo and showcase the novel features it provides to the community. See the [detailed requirements here](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain).

This issue is available for the reviewers of JOSS to discuss Ginkgo.

**Comment by adam-m-jcbs** [comment]
Hi all :wave: !  Just wanted to quickly mention I'll be a reviewer for JOSS.  I love seeing great projects submitted to JOSS!  I'm glad @pratikvn initiated this effort.

I will prepend my review issues with [JOSS REVIEW] and try to link back to the [JOSS issue](https://github.com/openjournals/joss-reviews/issues/2260) tracking this review.

**Comment by pratikvn** [comment]
@adam-m-jcbs and @zeroset, please let us know if you need anything else from our side to complete your review. We have addressed both the functionality aspects (pointed out by @adam-m-jcbs ) and the paper changes (requested by both @adam-m-jcbs and @zeroset ).

**Comment by mjsottile** [comment]
I made a note in the review issue (https://github.com/openjournals/joss-reviews/issues/2260#issuecomment-674607767) regarding some final changes to make to the bibliography.  Once those are complete we should be good.
