### ISSUE TITLE
separate third-party library group

### ISSUE THREAD

**Issue by yhmtsai** [ginkgo-project/ginkgo#482]
We collect all system third-party library in the same group in our [guideline](https://github.com/ginkgo-project/ginkgo/wiki/Contributing-guidelines#include-statement-grouping)
We also use the third-party library installed by Ginkgo as system third-party library in https://github.com/ginkgo-project/ginkgo/issues/343

In https://github.com/ginkgo-project/ginkgo/pull/447, the third-party libraries are bunched, so we probabliy need to separate them into two group.

If we need to separate the group, I would prefer to use device-wide libraries and the other third-party libraries.

any idea?

**Comment by upsj** [comment]
Sounds sensible to me! To avoid confusion I would probably call the device-wide libraries executor-specific or something similar.

**Comment by pratikvn** [comment]
Yes, sounds good to me as well, executor-wise into one and thirdparty into one sounds good.

**Comment by tcojean** [comment]
I also am OK with this, executor-wise and thirdparty is good.

**Comment by thoasm** [comment]
Sounds good to me. I also like the name @upsj suggested: `executor-specific`.

**Comment by yhmtsai** [comment]
We separate executor-specific and other third party libraries now.
Close via #447
