### ISSUE TITLE
Improve ISAI to handle an arbitrary number of elements per row

### ISSUE THREAD

**Issue by thoasm** [ginkgo-project/ginkgo#511]
The current Implementation of CUDA and HIP (from PR #502) can only handle `warp_size` elements per row. It would be nice if we could handle an arbitrary number of elements per row.
Currently, I see the following options:
1. Always do the generation on the CPU (the "host" executor)
2. Perform the generation on the proper device, and copy to the CPU to compute all rows that were not handled by the GPU, followed by copying back
3. Allocate additional GPU memory, which acts as temporary storage to do the dense solve. Might require an additional kernel launch to map the global memory storage to rows, so thread blocks would not override each other.
4. As @upsj explained in a [comment](https://github.com/ginkgo-project/ginkgo/issues/511#issuecomment-618581444), we could also build a sparse TRS instead of a dense one (in case it would be too large), and fall back to Lower/Upper triangular solves.

Option (1.) is the easiest to do, but also likely the slowest. Option (2.) also has a lot of overhead, but might be faster than option (1.) under some circumstances, but if the matrix is very dense, it might be even slower than (1.).
Option (3.) should perform the best, but is also the most complex to implement.

There might be even more options, so feel free to complete the list.

Also, as part of the improvement, we should move the copying of the sparsity pattern out of the compute kernel and do it in the `core` module. PR #508 adds the option to change the sparsity pattern of the inverse. We could avoid a matrix copy (and explicit zeros in the input matrix) by forwarding the non-changed CSR matrix and an inverse matrix with the desired sparsity pattern. This would result in changes to all kernels by removing the sparsity information copying and a change of the tests.

**Comment by upsj** [comment]
The size of the (dense) triangular systems grows quadratically with the number of non-zeros in the row, correct? But for such large rows, can it not also happen that the triangular system is relatively dense? It might be possible to fall back on the Lower/UpperTrs by building a triangular system of dimension (at worst) `nnz x nnz` that consists of one block per row that is too large. This should also provide a lot of parallelism to the triangular solve, right?
