### ISSUE TITLE
Adding `remove_complex` to norms in general inside Ginkgo

### ISSUE THREAD

**Issue by thoasm** [ginkgo-project/ginkgo#547]
We need to change multiple parts of our implementation if we want to properly support complex:
1. `Dense::compute_norm2` should put the result into a `Dense<remove_complex<ValueType>>`
  While using `squared_norm()` instead of `compute_dot` inside the kernels. Reference kernel example:
   https://github.com/ginkgo-project/ginkgo/blob/develop/reference/matrix/dense_kernels.cpp#L187
2. The `Convergence` logger should also use the non-complex storage type here:
   https://github.com/ginkgo-project/ginkgo/blob/develop/core/log/convergence.cpp#L61
3. The `ResidualNormReduction` stopping criterion should use the non-complex vector type: `using Vector = matrix::Dense<remove_complex<ValueType>>` here:
   https://github.com/ginkgo-project/ginkgo/blob/develop/include/ginkgo/core/stop/residual_norm_reduction.hpp#L71

There might be more, but these are the ones I could find this far.

_Originally posted by @thoasm in https://github.com/ginkgo-project/ginkgo/issues/534#issuecomment-634031364_

**Comment by tcojean** [comment]
@thoasm since I believe you already have this fixed somewhere, I attribute this issue to you

**Comment by thoasm** [comment]
@tcojean Yes, I am on it, thanks.
