### ISSUE TITLE
[JOSS REVIEW] Please clarify contributor criteria

### ISSUE THREAD

**Issue by adam-m-jcbs** [ginkgo-project/ginkgo#548]
Hi `ginkgo` developers :wave: !

This issue is part of a [JOSS review](https://github.com/openjournals/joss-reviews/issues/2260), tracked in-project with issue #479 .

To meet JOSS's authorship and credit requirements, "[T]he submitting author [has] made major contributions to the software [and] the full list of paper authors [is] appropriate and complete"

The submitting author (@pratikvn) has indeed made significant contributions, as have others listed as authors in `contributors.txt`.  Excellent!

However, some people with either Pull Requests or commits in the repo are not listed as contributors/authors.  While it is not necessarily the case that all people making contributions to the software are authors, the project should have clear criteria for authorship and make sure people that make contributions get due credit.

The following are not listed in `contributors.txt` but have made contributions to the code repository.  Please clarify the ginko-project's authorship/contribution criteria, and perhaps update the `contributors.txt` with any that fit this criteria but aren't listed:

+ Lukas Riemer (https://github.com/lksriemer): Has made a `ginkgo` PR and reviewed a PR.
+ Timo Heister (https://github.com/tjhei): Listed as contributor according to GitHub, has made at least one commit.

If those with commits in the code or making PRs aren't authors, please help the JOSS reviewers and the community understand why these people do no meet the criteria for authorship.

GitHub has [an article](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) on creating a `contributing.md` file to clarify both for the project and potential open source contributors what the benefits, responsibilities, rights, and expectations of authorship or contribution are, as well as who will be listed as an author or contributing developer.

While such a file is not required by JOSS nor this review, if the project does not want to maintain such a file I would at least like to know what the project's criteria are so I can know if the code meets JOSS's authorship standards.

**Comment by pratikvn** [comment]
Thank you @adam-m-jcbs for bringing this issue of contribution guidelines to our notice. We will soon add contributing guidelines as a Markdown file according to github recommendations. See PR #549 

Our criteria for for authorship of the JOSS paper would be addition of atleast an algorithm/kernel to our production code (develop branch). From a license and copyright perspective, it is necessary that we add people who have added some code to the repository be listed in the contributors.txt file. 

For the authorship on the JOSS paper, we believe that our criteria of a significant contribution should involve contribution of an algorithm or multiple kernels to our codebase. 

Regarding the two contributors you mention, we did not add Lukas Reimer as his contributions are not yet in our production branch and the contributions of Timo Heister do not satisfy our criteria.

**Comment by adam-m-jcbs** [comment]
Thanks for the clarification, @pratikvn !

It occurs to me that I should distinguish between the `contributors.txt` file and the JOSS paper authors.

My comments regarding a `Contributing.md` or similar file are in regard to the `contributors.txt` file and clarifying contribution credit for the project as a whole.

You have provided the clarification I needed for the review in regards to `contributors.txt`.

For the JOSS paper, the author list criteria you provide is very robust and in line with JOSS requirements, as I understand them.

Thank you for a quick and helpful response. I will certify the paper meets JOSS authorship standards and close this issue.
