### ISSUE TITLE
Should we document methods in std_extensions.hpp?

### ISSUE THREAD

**Issue by gflegar** [ginkgo-project/ginkgo#56]
The `std_extensions.hpp` file contains implementations of some useful standard utilities that are part of the C++14 and C++17 standards, but are not part of the C++11 standard (though they can be implemented in C++11).

For now, we are not documenting any of them, as there are documented in numerous online references about C++ ([the standard draft](http://eel.is/c++draft/), [cplusplus.com](http://www.cplusplus.com/), [cppreference.com](http://en.cppreference.com/w/)).

However, there is a proposal that we should stil provide some documentation for them, to make the documentation self-contained, and not require implementers of Ginkgo to look online for the documentation.

The purpose of this issue is to discuss if we should do this or not. Please use the thumbs up / thumbs down buttons to vote, and write comments if you want to clarify your position on this.

**Comment by gflegar** [comment]
I don't hink this is a good idea, mainly for 2 reasons:

*   the additions we implement are exclusively 1-liners for which it is clear from the code what they do (see how pointless is the documentation for them in the standard - e.g. for `make_unique`)
*   the whole point of having them is because they usually are a useful component in other things, so providing "useful" documentation would mean adding discussions about when to use these utilities and when not to use them in the source. This is not a one time documentation effort which doesn't change as long as the function doesn't change, but  something that evolves over time, as our understanding of these utilities gets better. If we are not happy with discussions about these utilities that are available online, we can start a wiki page about it, but I am strongly against putting something that's "evolving" into the documentation.

**Comment by tcojean** [comment]
In my opinion this should be done, and here is why:
1. We aren't sure we are fully standard compliant, so depending on the standard's documentation doesn't seem good practice
2. If these functions were integrated to begin with, and not others, it would be good to know why, what are they trying to solve and which functionality is actually important/provided so that we can maintain them properly
3. Usually these functions are helpers/replacements for existing functionalities in C++11, for developers it's useful to know why this is preferred (or not) over the default case.

**Comment by hartwiganzt** [comment]
Difficult. If we do not document it, people will be wondering where to find it. So we should at least point to a documentation. But what if (for any reason) the C++17std starts differing from our version? Let me go over the arguments:

> the additions we implement are exclusively 1-liners for which it is clear from the code what they do (see how pointless is the documentation for them in the standard - e.g. for make_unique)

Not an argument. Documentation should be independent of the complexity.

> so providing "useful" documentation would mean adding discussions about when to use these utilities and when not to use them in the source.

Could be that we start having discussions. But we may have discussions on anything... I feel we can avoid discussions by having a short documentation and an explanation why we use a certain feature.

> We aren't sure we are fully standard compliant, so depending on the standard's documentation doesn't seem good practice.

I expect the standard to give a good documentation. There may be no need to duplicate (copy+paste) that documentation, but maybe a short documentation, a statement why we prefer that feature, and a reference to the C++17 standard.

> Usually these functions are helpers/replacements for existing functionalities in C++11, for developers it's useful to know why this is preferred (or not) over the default case.

This is going back to the discussion point. Lets focus the documentation on avoiding this discussions.

**Comment by gflegar** [comment]
> We aren't sure we are fully standard compliant, so depending on the standard's documentation doesn't seem good practice. When we are sure we are standard compliant, we need to at least state which standard (there may be new functionalities in later standards which we will not support).

Standards are backward-compatible - anything written for the older standard is guaranteed to work in newer standards (unless it is explicitly marked as deprecated and removed in one of the following standards, but this only happens if there is a serious flaw in the concept - I think `auto_ptr` and `throw` declaration are the only major things where this is the case).
Also, I am sure __everything__ we have there is fully standard-compliant. If you think something is not, please let me know. (`make_unique` was not, but could have been easily modified to be standard compliant - which would be a better investment of time than duplicating documentation from elsewhere).

> If these functions were integrated to begin with, and not others, it would be good to know why, what are they trying to solve and which functionality is actually important/provided so that we can maintain them properly.

There is no need to maintain them - they do exactly what the standard says they should do. They were integrated because they do what the standard says they do, and that was useful somewhere. Others were not because they were not needed up to this point, but once they are needed, anyone can put the implementation in `std_extensions.hpp`. Should we document for each functionality in ginkgo where it's being used? That's not maintainable,  as it would require us to change the documentation every time we use that feature somewhere.

> Usually these functions are helpers/replacements/"shorteners" for existing functionalities in C++11, for developers it's useful to know why this is preferred (or not) over the default case, and the policy for their usage (always, only in one case, ...).

That is something that IMO belongs in the [Style guide](https://github.com/ginkgo-project/ginkgo/wiki/Contributing-guidelines#code-style), not the documentation. For everything we have at this point the answer to why it is preferred is either "there is not alternative" or "because it's shorter to write". And the policy for their usage "whenever you want/need to use them". You think we should document that? Sounds common sense to me.

> But what if (for any reason) the C++17std starts differing from our version? 

__The__ C++17 standard is the C++17 standard, it cannot "start differing". It is a fixed document. That would make it a new standard.

> Not an argument. Documentation should be independent of the complexity.

Yes, and it is documented - __in the standard, and several other online documentations__. Our thing is an implementation of something that already exists. I have no objections to copy-pasting useless documentation other than documentation being useless, and copy-pasting something that's already available somewhere. (It's even more useless that I had to waste time writing the last sentence in the first place.) Consider an example compiled from `make_unique` documentation taken from the standard and using the implementation from GCC's standard library (with parameter names modified to match in the documentation and in the implementation):

```c++
  /**
   * @internal
   * Returns: unique_­ptr<T>(new T(std​::​forward<Args>(args)...)).
   * Does not participate in the overload resolution unless T is not an array.
   */
  template<typename T, typename... Args>
    inline typename _MakeUniq<T>::__single_object
    make_unique(Args&&... args)
    { return unique_ptr<T>(new T(std::forward<Args>(args)...)); }

  /**
   * @internal
   * Returns: unique_­ptr<T>(new remove_­extent_­t<T>[n]()).
   * Does not participate in the overload resolution unless T is an array of unknown bound.
   */
  template<typename T>
    inline typename _MakeUniq<T>::__array
    make_unique(size_t n)
    { return unique_ptr<T>(new remove_extent_t<T>[n]()); }

  /**
   * @internal
   * Does not participate in overload resolution unless T is an array of known bound.
   */
  template<typename T, typename... Args>
    inline typename _MakeUniq<T>::__invalid_type   // I would argue that is just bad naming in GCC, and __invalid_type should be named __fixed_array or something similar
    make_unique(Args&&...) = delete;
```

This is one of the more complicated examples, so in most other cases it would be even more useless. Does adding this documentation based on the standard (which __is__ complete documentation, as the standard has to be complete, and document everything in enough detail for implementers to implement it) help you enough? I.e. if you saw this without documentation, would you be any more likely to have to google for it than with the documentation?

I do understand that everything should have documentation, but this is just blindly following rules, where they obviously don't apply. This is not something we invented, this is something that exists, and is well-known to anyone who knows a bit about modern C++.  If we do not expect that from our developers, and want to document it for them to understand, then we have to document the whole C++ standard library (at least everything we use in Ginkgo from it - and that's a lot of stuff). How do you propose to do that? That's something for the wiki, not the source code.

As another example, look at this one (the documentation here is from cppreference, not the standard - the standard seems to think that just providing a definition is good enough, and doesn't add any more text than just the source code of how it is defined):

```c++
namespace detail {
template <typename... Ts> struct make_void { using type = void; };
}  // namespace detail
/**
 * Utility metafunction that maps a sequence of any types to the type void.
 */
template <typename... Ts>
using void_t = typename detail::make_void<Ts...>::type;
```

Is this considered useful documentation? What would you put in here? Discussions on when to use `void_t` and when not to use it? This belongs in a wiki / tutorial, not the documentation.

> Could be that we start having discussions. But we may have discussions on anything... I feel we can avoid discussions by having a short documentation and an explanation why we use a certain feature.

This is again something for tutorials, not documentation. That's why we have wiki, issues, etc. We are not starting discussions and stating personal opinions in the source. "Explanation why we use something" is a discussion. And why would C++14/17 features be any different than C++11 features? Do we create a source file which doesn't implement anything but just discusses smart pointers? No - that's why we have a [wiki page](https://github.com/ginkgo-project/ginkgo/wiki/Design-choices), and we can do the same in this case. It's just that source code is not the place for it.

> I expect the standard to give a good documentation. There may be no need to duplicate (copy+paste) that documentation, but maybe a short documentation, a statement why we prefer that feature, and a reference to the C++17 standard.

The standard does already have short documentation for all of the things we use, I'm trying to point out that all that documentation is pointless, so it's even more pointless to copy-paste it. The whole point of having those functionalities is not because they do anything "useful" by themselves (I feel I'm repeating myself for the 10th time here), but they are supposed to be used in combination with other things (think of them as extensions of missing stuff in the core language - you wouldn't document what the `for` keyword does, or would you?). And that is stuff for tutorial, not in-source documentation.

As a final example, see this gem:

```c++
/**
 * Helper type for std::enable_if.
 */
template <bool B, typename T = void>
using enable_if_t = typename std::enable_if<B, T>::type;
```

The "documentation" is once again based on cppreference, as once again the standard (note that this is a more than 1000 page document, so they are quite thorough in documenting everything) didn't find it necessary to provide any documentation in addition to the definition itself (and I tend to agree with them).

--------------

Finally, I would appreciate it if in future discussions we all think about other people's time and value it more then our own, and at least make the effort to research the topic of discussion in more detail before commenting and deciding on it.

**Comment by pratikvn** [comment]
After reading everything here, I would have to say that I agree with @gflegar. There is already a note that says 

>// For documentation about these utilities refer to the newer version of the
// standard.

As long as we implement the exact same thing the standard implements, I think this statement is sufficient. Maybe for more clarity we could just mention which standard each of these utilities comes from. `void_t` from C++17, `enable_if_t` and `conditional_t` from C++14 and for any other utilities we add in the future.

And also the exact same code as in the std_extensions.hpp file is in the cppreference of that utility, it should give more information on the utility along with other info as needed.
Another aspect is that probably in the future, we would adopt the C++14/17 compilers in Ginkgo as well as it becomes more widely adopted, then I guess this file would no longer be required.

**Comment by tcojean** [comment]
>Standards are backward-compatible - anything written for the older standard is guaranteed to work [...]
That is not the point. The point is that we implement one standard of things. Look at `std::unique_ptr`, `operator<<` only appears in C++20 but `unique_ptr` itself is a C++11 thing. Most `std` class or functionality has this behavior where things appear standard after standard, certainly they don't disappear. If we implement a function at standard version `X`, we need to notify this because maybe at version `X+Y` things will change and we will not be feature full against version `X+Y` but only `X`, so the standard documentation doesn't apply to us anymore. Or we need people to keep our code up to ensure compatibility with the **outsourced documentation**.

>There is no need to maintain them - they do exactly what the standard says they should do.
Again, which standard which version with which functionality.

>They were integrated because they do what the standard says they do, and that was useful somewhere. 
"The standard gives that functionality so we should do it too" is not a reason for doing something, even more so when we are leaving ourselves at C++11. Do stay at version 11 or do we implement every new standard functionality as we find a case where we would use it? To me breaching a rule is worth documentation. Not so much as to what the thing does, but as to why we went against the policy of having a C++11 code.

>That is something that IMO belongs in the Style guide, not the documentation. For everything we have at this point the answer to why it is preferred is either "there is not alternative" or "because it's shorter to write".
They are implementable using C++11 so the functionality exists. In addition, refer to the previous point. The documentation I showed as example for `make_unique` was not so much about its functionality, but about why it's implemented/needed in the code. I don't want documentation duplication, just to be clear with which version of the standard is implemented and if there is a particular reason to go against the C++11 code policy. Because none of that is clear.

**Comment by gflegar** [comment]
> If we implement a function at standard version X, we need to notify this because maybe at version X+Y things will change

They won't: this would break backward compatibility (yes backward compatibility is the point here!). New functions might get added, but existing functionalities will stay the same (they may only change the signature, add `constexpr` or `noexcept`, but you see  that without extra documentation anyway).
In any case, why would you need to change the documentation of function `X` if function `Y` gets added?

 > Yes either of those are annoying, but incorrect documentation is the worst thing you can have in your code.

Exactly my point! Why document and maintain something if that is already documented and maintained by someone else?

> Again, which standard which version with which functionality.

Every standard, every version, every functionality from the point when that functionality was introduced - backward compatibility!

> "The standard gives that functionality so we should do it too" is not a reason for doing something, even more so when we are leaving ourselves at C++11. Do stay at version 11 or do we implement every new standard functionality as we find a case where we would use it? To me breaching a rule is worth documentation. Not so much as to what the thing does, but as to why we went against the policy of having a C++11 code.

Where are we breaching any rules? The thing still compiles perfectly with any C++11 compliant compiler.
You sound like you think we use C++11 because we don't like newer standards, so implementing anything from those standards ourselves is considered blasphemy. I would love to use C++14 and even C++17 if it were possible. The only problem is that compilers we need to support don't support newer standards.
And yes, I am all for adding anything useful and not too complicated to implement from the newer standards - do you see a reason why not?

> but about why it's implemented/needed in the code.

Because it's useful, if you want to know where, `grep -r "the thing you're interested in" *`.
For all that "breaching rules" stuff you have in this paragraph, see my previous point.
We didn't make up a C++11 religion, it was imposed on us, so anything we can do to make our lives simpler, let's do it.

> I might add: ...

Is there a point relevant to this discussion here? You can always buy the $200 standard if you're not happy with the draft and online references - I am quite happy with it, and so is a bunch of other people.

> Here is an example of what I feel is a useful documentation

I don't fell it's useful, but irrelevant and redundant:

>  Helper type

`using name = /* some type */;` defines a type alias, for me "type alias" = "helper type". Didn't find out anything I didn't already know from this part of thedocumentation.

> from the C++14 standard

Why would I care? It's obviously not from the C++11 or a previous standard, as then I wouldn't have to define it. Whether it's form C++14 or C++17 (or the C++20 draft) makes no difference as it does the same thing in all of them (due to backward compatibility!).

> added for convenience due to repeated use.

And why else would I define a type alias? Must be because I was bored.

**Comment by gflegar** [comment]
Ok, I see there's no easy solution to this, so I propose the following compromise:

We document only the features which do different things in different standards (from the point when they were introduced in the standard), and say which standard we "follow".

(Please add thumbs up / thumbs down to the comment to vote)

**Comment by hartwiganzt** [comment]
> We document only the features which do different things in different standards (from the point when they were introduced in the standard), and say which standard we "follow".

I guess this requires deep research each time, correct?

**Comment by tcojean** [comment]
>You sound like you think we use C++11 because we don't like newer standards, so implementing anything from those standards ourselves is considered blasphemy. I would love to use C++14 and even C++17 if it were possible. The only problem is that compilers we need to support don't support newer standards.
>And yes, I am all for adding anything useful and not too complicated to implement from the newer standards - do you see a reason why not?

Where is the line.

>They won't: this would break backward compatibility (yes backward compatibility is the point here!).
No it is not. X and Y are not functionalities they are std versions. Again, look at unique_ptr. the whole unique_ptr functionality or at `make_shared`. You will see at standard 11 we have only one function, at function 20, 4 new functionalities are added. If we had coded something with standard 11 in mind and state juste look at the last standard version for documentation, then our documentation is wrong.

>And why else would I define a type alias?

We're not only talking about them here as you clearly stated that you may add other functionalities. And there was the `make_unique` also. If we consider that one, it could be for security, to enforce a new policy (with make_unique you should not need any `new`) and a lot of other things. Which could all very simply be documented in one line as my example and we know what to expect.

**Comment by gflegar** [comment]
> I guess this requires deep research each time, to find out whether this is the case for a specific feature, correct?

Far less research than this discussion is taking already, once every 3 years. And I'm convinced that we won't have such a situation. This proposal is just because Terry is not convinced. My guess is this will require 0 maintenance.

> Where is the line.

Why would we need "a line"?

> In make_shared you will see at standard 11 we have only one function, at version 20, 4 new functionalities are added.

These are 4 different overloads - every one of them is a separate function, distinct from the one in C++11. The one from C++11 still does exactly the same thing in C++20. Our `make_shared` for non-arrays would stil be valid, it's just that we wouldn't have the other overloads. We never claim that we maintain a full extension of the standard (as that is impossible).

> the implementation you used makes sense only pre C++14

Why wouldn't it make sense in C++14? It works just the same in any of the standards.  True, you can simplify it in C++14 onward, but there's no need to do it if we already have a working implementation (there's also no performance benefits in doing it).

> Documentation on some sort of ginkgo specific usage and maintenance aspects can be immensely useful.

You are talking about hypothetical situations. Non of that is needed now - there are no maintenance aspects, or ginkgo-specific usage in anything we have now. If there are in future stuff, we can sure add a comment to affected implementations. I don't se a reason to add meaningless comments just to have comments on everything, because at some point in the future we _may_ want to add a comment on one of them.

> with make_unique you should not need any new in the code at all

This statement is just completely wrong.

> Which could all very simply be documented in one line as my example and we know what to expect.

And this can be done, __for functionalities where such implementation is required__, there's no such thing for now. So you're fighting for something that that might be useful in a hypothetical situation which may never happen.

Look, I'm done discussing this, because this is pointless. I tried explaining in detail why creating such a rigid rule doesn't make any sense, I even tried a compromise, but you're refusing to budge one bit. I won't waste any more of my time on this. There are more important things in Ginkgo than having a 10 page discussion over a 50 line file with functionalities so trivial even the standard doesn't see it necessary to document them, and places where better documentation is needed more than adding some useless lines here which tell you nothing new (e.g. the solvers).

If you get a majority vote on this, do a PR with the changes and I'll accept it even if it's useless, just as long as there's nothing wrong in it.

**Comment by hartwiganzt** [comment]
OK, let's move this fight back to a fruitful discussion. I give four sections with alternatives, please add advantage (+) and disadvantages (-) that I missed in my post.

Document all functionality
===================
++ Documentation self-contained
++ Users will (hopefully) understand why we add a specific feature
-- We duplicate documentation that is in the C++ standard
-- If the feature changes, we need to update the documentation, keep track


Document functionality that is different in different standards
===================
++ We reduce duplication of documentation
++ In the best case, the motivation to use of features is clear
-- We have an inconsistency as some features are documented, not all
-- We need to keep track of that

No documentation, refer to the C++ standard
===================
++ We do not duplicate documentation
++ As we move to newer C++ standards, this file can be skipped
-- Developers/users may ask why a certain feature is not documented & what it does
-- Users may ask why we use specific features of later C++ versions

**Comment by gflegar** [comment]
I suggest we start writing this document on the wiki (easier to collaborate than with PRs), and once it's in a good state, we move it into the core repo.

**Comment by gflegar** [comment]
I think we reached a conclusion here, closing this.
