### ISSUE TITLE
Ranges

### ISSUE THREAD

**Issue by gflegar** [ginkgo-project/ginkgo#58]
__Note:__ this issue was moved from Gitlab: https://gitlab.com/ginkgo-project/ginkgo/issues/74

It is often required to obtain a sub-range of an array or a matrix, for example when designing algorithms that work with matrix blocks. Formalizing this in a `range` concept and defining classes which implement it would have several benefits:

*   it removes the need for error-prone arithmetic involving pointer offsets, sizes and "_ldas_" to implement sub-ranges,
*   it reduces the number of function parameters and bugs due to wrong dimensions, as each range contains information about the pointer, the size, and the shape of the range,
*   it abstracts away memory access so additional facilities can be added: e.g. out-of-bound checking in debug mode, access to values types stored in structure-of-arrays format (think of the new idea of splitting a double number as `s|eeeeeeeeeee|mmmmmmmmmmmmmmmmmmmm||mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm` and storing the two halves separately),
*   it implements the same relationship as standard library containers and iterators - the first one "owns" the data, and the second one is used to manipulate it without carrying any data ownership semantics

How I imagine the interface to look like is something like this (inspired by the [Armadillo library](http://arma.sourceforge.net/docs.html#submat)):

```c++
template <typename Range>
void range_example(Range r)
{
    constexpr int dims = Range::num_dimensions; // get the number of dimensions in the range (1 for vec, 2 for matrix, should also support tensors)
    constexpr auto order = Range::storage_order;  // get the storage order of the range - row-major/column-major (1)
    static_assert(dims >= 2, "This only works for ranges with at least 2 dimensions");
    auto elem = r(3, 4); // get element at position (3, 4), if the range has more dimensions all the trailing dimensions are set to 0s
    auto sub_range = r(span(end - 3, end), span()):  // get subrange (end - 3:end, 0:end, 0, ...) of the range (2), (3)
    r((span(0, 3), span()) = sub_range;  // copy sub-range, range implementation can optimize the copy for the storage scheme
    auto r2 = r.reshape(4, 5, 2);  // reshape the range to size (4, 5, 2);
    auto s = size(r2);  // get the size of a range, in this case (4, 5, 2);
}
```

(1) maybe we could also have this as a list of dimension indexes - the implementation could be easier, and it is a more flexible solution for multidimensional ranges  
(2) `span` is the name they use in armadillo, maybe we can think of something better - but should be both clear and short, as we'll use it all the time, and also shouldn't clash with any other "usual" names  
(3) `end` could cause a lot of name clashes - not sure how to solve this, it has to be descriptive and short, but I am worried about `end`, maybe `npos`, as this will be familiar for anyone that used `std::string`?

**Comment by hartwiganzt** [comment]
Without suggesting this, I want to mention the Matlab notation (1-based):
```
M(4:end,:) = M(4:end,1:end);
M(4:2:end,1) = [ M(4,1) M(6,1) M(8,1) M(10,1) ... ] // all odd elements
```
https://de.mathworks.com/company/newsletters/articles/matrix-indexing-in-matlab.html

**Comment by gflegar** [comment]
If you're not suggesting it, then how should I interpret your post? :confused:

**Comment by upsj** [comment]
Related to #1115, this will most likely not happen in Ginkgo, but std::mdspan should provide an adequate implementation in the future.
