### ISSUE TITLE
Segfaults due to executor generation in examples

### ISSUE THREAD

**Issue by upsj** [ginkgo-project/ginkgo#594]
Some of our examples use an executor map
```cpp
std::map<std::string, std::shared_ptr<gko::Executor>> exec_map{
    {"omp", omp},
    {"cuda", gko::CudaExecutor::create(0, omp, true)},
    {"hip", gko::HipExecutor::create(0, omp, true)},
    {"reference", gko::ReferenceExecutor::create()}};
```

Executing these tests with HIP and CUDA compiled causes a segmentation fault in my tests, probably due to the CUDA and HIP executor destroying the same device and/or library handles (hipSPARSE etc.)

This should be fixed by only creating the executor on demand, like in the benchmark examples (replacing std::shared_ptr<...> by std::function<std::shared_ptr<...>()> and using lambdas)

**Comment by yhmtsai** [comment]
The issue should be caused by `device_reset` when cuda/hip on the same device.
When the first one of cuda/hip is destroyed, it call the device_reset because it own `num_execs` is zero.
Thus, the running stuff on the second one will run on the empty.

I discussed it with @tcojean before, and he has some idea to fix it.

**Comment by upsj** [comment]
I vaguely recall us also having some issues with cuSPARSE handles being destroyed twice or something similar? Or was that also caused by the device reset?

**Comment by greole** [comment]
I created a PR. But I was wondering, since creating executors by its name is such a common operation, if it should be moved to a dedicated function?

**Comment by upsj** [comment]
I'm not entirely sure about this. Since these are examples, they should be as self-contained as possible, and I'm not sure whether users would need this functionality in the library.
