### ISSUE TITLE
Do not execute the minimal-cuda-solver example

### ISSUE THREAD

**Issue by nghiakvnvsd** [ginkgo-project/ginkgo#599]
I have a problem when I run the minimal-cuda-solver example. It does not work but it also does not report an error.
I build with: cuda 10.2, g++ 7.5.0. I think It is not an error. Thank you!

**Comment by upsj** [comment]
`minimal-cuda-solver` requires input from the user, so you need to concatenate the inputs together and pipe them to the example, see [the example documentation](https://ginkgo-project.github.io/ginkgo/doc/develop/minimal_cuda_solver.html):

```
cat data/A.mtx data/b.mtx data/x0.mtx | ./minimal_solver_cuda
```

**Comment by nghiakvnvsd** [comment]
Thank you very much!
