### ISSUE TITLE
[ERROR] when combine GINKGO and MFEM

### ISSUE THREAD

**Issue by nghiakvnvsd** [ginkgo-project/ginkgo#615]
Hi everybody! It's my first time to combine MFEM and GINKGO. I have a problem when I try buildding ginkgo example(https://github.com/mfem/mfem/tree/master/examples/ginkgo) by make
It reports:

g++ -O3 -std=c++11 -I../.. -isystem ../../../ginkgo/install/include ex1.cpp -o ex1 -L../.. -lmfem -Wl,-rpath,../../../ginkgo/install/lib -L../../../ginkgo/install/lib -lginkgo -lginkgo_omp -lginkgo_cuda -lginkgo_reference -lrt
/usr/bin/ld: /tmp/cc5d3Sta.o: undefined reference to symbol '_ZNK3gko11OmpExecutor11raw_copy_toEPKNS_11HipExecutorEmPKvPv'
//usr/local/lib/libginkgo_hip.so.1.2.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
makefile:42: recipe for target 'ex1' failed
make: *** [ex1] Error 1

I have no idea about it. I have already run all examples except the ginkgo example. May you help me fix it?

Thanks!

**Comment by upsj** [comment]
Thanks for reporting this issue! Just a hunch: can you try adding `-lginkgo_hip` to the command line?

**Comment by nghiakvnvsd** [comment]
I only type: make

**Comment by nghiakvnvsd** [comment]
and when I type: ../.. -isystem ../../../ginkgo/install/include ex1.cpp -o ex1 -L../.. -lmfem -Wl,-rpath,../../../ginkgo/install/lib -L../../../ginkgo/install/lib -lginkgo -lginkgo_omp -lginkgo_cuda -lginkgo_reference -lrtg++ -O3 -std=c++11 -I../.. -isystem ../../../ginkgo/install/include ex1.cpp -o ex1 -L../.. -lmfem -Wl,-rpath,../../../ginkgo/install/lib -L../../../ginkgo/install/lib -lginkgo -lginkgo_omp -lginkgo_cuda -lginkgo_reference -lrt -lgingk_hip 

it reports:

ex1.cpp:(.text.startup+0xf32): undefined reference to `mfem::GinkgoWrappers::CGSolver::CGSolver(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, double, double, gko::LinOpFactory const*)'
ex1.cpp:(.text.startup+0xf4f): undefined reference to `mfem::GinkgoWrappers::GinkgoIterativeSolverBase::solve(mfem::SparseMatrix const*, mfem::Vector&, mfem::Vector const&)'
collect2: error: ld returned 1 exit status

**Comment by upsj** [comment]
Maybe @nbeams or @pratikvn can tell you more here, since they both worked on the MFEM integration before. It looks to me like the latest MFEM branch is slightly incompatible with Ginkgo version >= 1.2, since it doesn't add a dependency to the HIP backend.

**Comment by pratikvn** [comment]
Can you try checking out ginkgo at 1.1.1 instead of 1.2.0 ? `git checkout v1.1.1` ? And use this to compile with MFEM ?

**Comment by nghiakvnvsd** [comment]
> Can you try checking out ginkgo at 1.1.1 instead of 1.2.0 ? `git checkout v1.1.1` ? And use this to compile with MFEM ?

Do you mean I have to uninstall ginkgo 1.2.0 and install ginkgo 1.1.1?

**Comment by pratikvn** [comment]
Or in a new directory. However you prefer. MFEM wrappers only support Ginkgo with version <=1.1.1.

**Comment by nghiakvnvsd** [comment]
> Or in a new directory. However you prefer. MFEM wrappers only support Ginkgo with version <=1.1.1.

Sorry to bother you. When I installed ginkgo 1.2.0, I followed tutorial 1 (https://github.com/ginkgo-project/ginkgo/wiki/Tutorial-1:-Getting-Started). Now, I install ginkgo 1.1.1, I download source code (https://github.com/ginkgo-project/ginkgo/releases/tag/v1.1.1) but in the step: cmake .. it reports: 

 CMake Error at CMakeLists.txt:159 (add_dependencies):
   Cannot add target-level dependencies to non-existent target "format".

   The add_dependencies works for top-level logical targets created by the
   add_executable, add_library, or add_custom_target commands.  If you want to
   add file-level dependencies see the DEPENDS option of the add_custom_target
   and add_custom_command commands.

I try doing next step but when I type : make -j4 . it reports: make: *** No targets specified and no makefile found.  Stop.

I think I have a mistake when I running ccmake .. . I dont know how to fix. I have no background about install a new opensource library, I only follow the turorial.

**Comment by pratikvn** [comment]
I believe we used to have `GINKGO_DEVEL_TOOLS=on` by default with <=1.1.1, but changed it to `off` from 1.2.0, So, maybe you can try `cmake -DGINKGO_DEVEL_TOOLS=off ..` ?

**Comment by nghiakvnvsd** [comment]
> I believe we used to have `GINKGO_DEVEL_TOOLS=on` by default with <=1.1.1, but changed it to `off` from 1.2.0, So, maybe you can try `cmake -DGINKGO_DEVEL_TOOLS=off ..` ?

/home/ubuntu/ginkgo/cuda/test/solver/lower_trs_kernels.cpp:40:10: fatal error: cuda.h: No such file or directory
 #include <cuda.h>
          ^~~~~~~~
compilation terminated.
cuda/test/solver/CMakeFiles/cuda_test_solver_lower_trs_kernels.dir/build.make:62: recipe for target 'cuda/test/solver/CMakeFiles/cuda_test_solver_lower_trs_kernels.dir/lower_trs_kernels.cpp.o' failed
make[2]: *** [cuda/test/solver/CMakeFiles/cuda_test_solver_lower_trs_kernels.dir/lower_trs_kernels.cpp.o] Error 1
CMakeFiles/Makefile2:1944: recipe for target 'cuda/test/solver/CMakeFiles/cuda_test_solver_lower_trs_kernels.dir/all' failed
make[1]: *** [cuda/test/solver/CMakeFiles/cuda_test_solver_lower_trs_kernels.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/ubuntu/ginkgo/cuda/test/solver/upper_trs_kernels.cpp:40:10: fatal error: cuda.h: No such file or directory
 #include <cuda.h>
          ^~~~~~~~
compilation terminated.
cuda/test/solver/CMakeFiles/cuda_test_solver_upper_trs_kernels.dir/build.make:62: recipe for target 'cuda/test/solver/CMakeFiles/cuda_test_solver_upper_trs_kernels.dir/upper_trs_kernels.cpp.o' failed
make[2]: *** [cuda/test/solver/CMakeFiles/cuda_test_solver_upper_trs_kernels.dir/upper_trs_kernels.cpp.o] Error 1
CMakeFiles/Makefile2:1984: recipe for target 'cuda/test/solver/CMakeFiles/cuda_test_solver_upper_trs_kernels.dir/all' failed
make[1]: *** [cuda/test/solver/CMakeFiles/cuda_test_solver_upper_trs_kernels.dir/all] Error 2
[ 36%] Linking CXX executable cgs_kernels
[ 36%] Built target cuda_test_solver_cgs_kernels
[ 36%] Linking CXX executable ir_kernels
[ 36%] Built target cuda_test_solver_ir_kernels
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tcojean** [comment]
Indeed there was an issue with 1.1.1 with these examples. There are two ways you can go about fixing this, I believe.

1.  You need can use this fix here https://github.com/ginkgo-project/ginkgo/pull/452
2. Another way to fix this is probably to export the following environment variables (make sure to replace `/usr/local/cuda/include` with your actual CUDA include path):
```bash
export CUDA_INC_PATH=/usr/local/cuda/include
export INCLUDE_PATH=/usr/local/cuda/include:$INCLUDE_PATH
export C_INCLUDE_PATH=/usr/local/cuda/include:$C_INCLUDE_PATH
export CXX_INCLUDE_PATH=/usr/local/cuda/include:$CXX_INCLUDE_PATH
```

**Comment by nghiakvnvsd** [comment]
sorry to bother you again because I tried many ways. Do you mean
in /ginkgo/build I type:

export CUDA_INC_PATH=/usr/local/cuda/include
export INCLUDE_PATH=/usr/local/cuda/include:$INCLUDE_PATH
export C_INCLUDE_PATH=/usr/local/cuda/include:$C_INCLUDE_PATH
export CXX_INCLUDE_PATH=/usr/local/cuda/include:$CXX_INCLUDE_PATH

and then type: make -j4? Sorry when I dont understand it :(

**Comment by pratikvn** [comment]
You need to first do `which nvcc` and if say it returns a path `/usr/local/cuda/bin/nvcc`, then use `export CUDA_INC_PATH=/usr/local/cuda/include` and so on, but if `which nvcc` returns `/opt/cuda/bin/nvcc` , then you need to do `export CUDA_INC_PATH=/opt/cuda/include` and so on.

**Comment by nghiakvnvsd** [comment]
when I ran which nvcc it returns /usr/local/cuda/bin/nvcc then I type:

export CUDA_INC_PATH=/usr/local/cuda/include
export INCLUDE_PATH=/usr/local/cuda/include:$INCLUDE_PATH
export C_INCLUDE_PATH=/usr/local/cuda/include:$C_INCLUDE_PATH
export CXX_INCLUDE_PATH=/usr/local/cuda/include:$CXX_INCLUDE_PATH

then I type: make -j4 but It still says the samething

**Comment by nghiakvnvsd** [comment]
If you do not mind, May you help me though teamview?

**Comment by pratikvn** [comment]
You maybe can try to run `cmake` again. In any case, you could also switch off tests in case you you don't plan on running any tests (you can do this by passing `-DGINKGO_BUILD_TESTS=off` to cmake).

**Comment by nghiakvnvsd** [comment]
> You maybe can try to run `cmake` again. In any case, you could also switch off tests in case you you don't plan on running any tests (you can do this by passing `-DGINKGO_BUILD_TESTS=off` to cmake).

everything does work. Thank you very much!!!
