### ISSUE TITLE
does it support multi-gpu or multicores cpu.

### ISSUE THREAD

**Issue by ztdepztdep** [ginkgo-project/ginkgo#637]

**Comment by upsj** [comment]
This depends on what you mean by multi-GPU. You can use multiple GPU executors in parallel by specifying different device IDs, but true multi-GPU as well as multi-node support for distributed matrices is currently still under development.
The OpenMP executor allows you to fully utilize multicore CPUs, but it is not highly tuned for performance yet.

**Comment by ztdepztdep** [comment]
Thanks. I have noticed that only the iterative solver is provided in the solver factory. I want to know that does it supports a dense direct solver.

**Comment by upsj** [comment]
Ginkgo is primarily a sparse numerical linear algebra library, so we do not support dense direct solvers right now. That may change in the future, but for now, the answer is unfortunately no.
