### ISSUE TITLE
Implement atomic operations for custom value types

### ISSUE THREAD

**Issue by gflegar** [ginkgo-project/ginkgo#65]
The current implementation of atomic operations (introduced in #57 and #64) does not support custom value types.  Ginkgo will compile, but attempts of using it will result in assertions failures.

We should explore the possibility of general mutex functionalities for GPUs,  which would allow us to implement atomics. They won't be extremely fast, but will at least work correctly.

**Comment by gflegar** [comment]
This is to difficult to do for 1.0. Will have to wait.

**Comment by upsj** [comment]
It seems like this was already completed with #310, now unsupported types already fail at compile-time
