### ISSUE TITLE
Undefined symbols after installation for executor

### ISSUE THREAD

**Issue by nabw** [ginkgo-project/ginkgo#678]
Hi everyone, I am installing Ginkgo to use it with deal.II (from deal and not from Ginkgo as in your example). For this, I successfully compiled the entire library with CUDA and HIP support as well as passed all tests. After this, I installed the library, for which I get some missing symbols that halt dealII compilation:

```
    lib/libdeal_II.so.9.3.0-pre: error: undefined reference to 'typeinfo for gko::HipExecutor'
    ../lib/libdeal_II.so.9.3.0-pre: error: undefined reference to 'gko::OmpExecutor::raw_copy_to(gko::HipExecutor const*, unsigned long, void const*, void*) const'
    ../lib/libdeal_II.so.9.3.0-pre: error: undefined reference to 'gko::OmpExecutor::raw_copy_to(gko::DpcppExecutor const*, unsigned long, void const*, void*) const'
```

I checked the installed library and it is indeed the case: 

```
ginkgo/lib > nm -gDC libginkgo_omp.so | grep " U " | grep raw_copy
        U gko::OmpExecutor::raw_copy_to(gko::HipExecutor const*, unsigned long, void const*, void*) const
        U gko::OmpExecutor::raw_copy_to(gko::CudaExecutor const*, unsigned long, void const*, void*) const
        U gko::OmpExecutor::raw_copy_to(gko::DpcppExecutor const*, unsigned long, void const*, void*) const
```

I'm not sure what the typeinfo reference means, but maybe the following is meaningful to someone: 

```
ginkgo/lib > nm -gDC libginkgo_hip.so | grep " U " | grep typeinfo
                 U typeinfo for decltype(nullptr)
                 U typeinfo for int
                 U typeinfo for long
                 U typeinfo for std::bad_weak_ptr
                 U typeinfo for std::exception
                 U typeinfo for void
```

I noticed that the missing OmpExecutor::raw_copy_to methods are defined inside the other executors, i.e in 

```
ginkgo/hip/base/executor.hip.cpp
ginkgo/dpcpp/base/executor.dp.cpp
```
Just for the sake of testing, I moved the function definition (with all undefined methods commented) to a new file 

```ginkgo/omp/base/executor.omp.cpp```

which cured the undefined raw_copy_to methods in the installation folder (but I'm not sure about what will be broken). For the other error, I don't know how to proceed. Let me know your thoughts.

NB

**Comment by pratikvn** [comment]
Hello @nabw , It is possible that there is a version conflict. Can you please try with an earlier version of Ginkgo, say 1.1.1 ?

**Comment by upsj** [comment]
To elaborate on this, deal.II only links against `ginkgo, ginkgo_reference, ginkgo_omp` and `ginkgo_cuda`, but not `ginkgo_hip`, which contains the missing symbols, since the CPU-GPU copy always need to involve the GPU runtime API. This likely needs to be updated in deal.II upstream.

**Comment by pratikvn** [comment]
Thanks @upsj. I will create a PR on deal.ii's end to fix this soon.

**Comment by nabw** [comment]
Ok, so apparently the problem arises from the fact that hip, cuda, dpcpp and reference libraries are different objects and so deal.II was indeed not only missing HIP but also DPCPP in its cmake directives. I will send the pull request in a while. I believe this can be closed. Thanks for the help!

**Comment by upsj** [comment]
@nabw If you installed Ginkgo in the default location, the precense of the `Ginkgo-config.cmake` should already be enough for `find_package(Ginkgo)` to work, so if you are looking to fix this yourself, it might make sense to simplify the whole CMake integration. The preferred way to link to Ginkgo would be `target_link_libraries(target Ginkgo::ginkgo)`, since that forwards these transitive link dependencies automatically, including include directories and potentially compiler flags that were used to build Ginkgo.
