### ISSUE TITLE
Improvements to Doxygen

### ISSUE THREAD

**Issue by gflegar** [ginkgo-project/ginkgo#76]
Taken from comments on PR #75 
--------------------

Here are some changes that may be worth considering?

To document functions which are standalone (e.g. `gko::transpose`), then either:
+ the namespace should be documented (`gko` namespace here)
+ the file should be documented
Source: https://stackoverflow.com/questions/2794054/documenting-functions-in-c-with-doxygen

In addition, if we want to include some functions inside the documentation of a class, such as the operators and `transpose` for dim, I think the only solution is the following:
+ at the beginning of the related function declarations, insert `\memberof dim @{`
+ at the end of the function declarations, close the block `/** @} */`

Finally, at some point, we may want to also document the `master` branch separately, do we already prepare a location for that and add `master` as a target for documentation deployment?

**Comment by tcojean** [comment]
Another point to consider here, we may want to have some form of main page to structure the documentation, give some information about Ginkgo, etc.

There are many examples online including in important projects. [Here](http://alesnosek.com/blog/2015/06/21/the-structure-of-doxygen-documentation/) is one example of a simple setup.
