### ISSUE TITLE
Load data from file instead of std::cin in minimal-cuda-solver

### ISSUE THREAD

**Issue by neozhang307** [ginkgo-project/ginkgo#767]
Might be a relative naive problem.

I tried to modify the minimal-cuda-solver code to accept input from ifstream. I keep run into error:

     terminate called after throwing an instance of 'gko::AllocationError'

The code changed listed as follow:

    // auto A = gko::read<gko::matrix::Csr<>>(std::cin, gpu);
    // auto b = gko::read<gko::matrix::Dense<>>(std::cin, gpu);
    // auto x = gko::read<gko::matrix::Dense<>>(std::cin, gpu);
    
    auto A = gko::read<gko::matrix::Csr<>>(std::ifstream("data/A.mtx"), gpu);
    auto b = gko::read<gko::matrix::Dense<>>(std::ifstream("data/b.mtx"), gpu);
    auto x = gko::read<gko::matrix::Dense<>>(std::ifstream("data/x0.mtx"), gpu);

I tried to used gdb to understand what implementation assumptions inside the code. But I could not jump the location of "read" function. I guess the calling stack is a little complex.

**Comment by pratikvn** [comment]
Hello @neozhang307 . The modifications above work for me and I can successfully run the example. `gko::AllocationError` probably means that allocations on your CUDA device are failing. Can you run other CUDA code ? Is your GPU working  as expected ?

**Comment by upsj** [comment]
On your issues with GDB, if you don't give any additional input, Ginkgo is built in Release mode, which contains no debugging information and thus no binary-to-source line mapping. What you could try is to add a
```cpp
try {
    ...
} catch (gko::Error& err) {
    std::cerr << err.what();
}
```
block around the example code, or if that doesn't give any insights, recompile Ginkgo with CMAKE_BUILD_TYPE=Debug and check using `gdb`.

**Comment by neozhang307** [comment]
Thanks a lot. I thought there might be something wrong with my code. 

I run the minimal-cuda-solver in both P100 and A100 chips. The test code and my altered code run successfully in A100. But in P100 both codes throw allocation errors. 
I am using the data provided in ./minimal-cuda-solver/data so I think the problem should not be allocating too large memory. I guess the problem might be that cmake did not generate code for other GPU platforms by default? 
I am trying to recompile Ginkgo with: 

    -DGINKGO_CUDA_ARCHITECTURES="Pascal;Volta;Ampere" instead of using Auto

It takes time. Will update the status tomorrow. 

For debug. I did enable Debug flag. But I just noticed a warning inside gdb:

    Missing separate debuginfos, use: debuginfo-install cuda-cudart-11-3-11.3.58-1.x86_64 libX11-1.6.7-3.el7_9.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libxcb-1.13-1.el7.x86_64

I guess this might be the problem. I would turn to my system admin for help tomorrow.

**Comment by upsj** [comment]
It's great to hear that you got things to work! The issue seems to be a bit convoluted, in case you still have the original (broken) setup, could you send us a backtrace (type `bt` in gdb after the exception has been thrown) so we can see where this empty allocation takes place? We might need to take care of this on our end, since we assume allocations to always return a non-null pointer. I have no idea where `No protocol specified` could be coming from, I am not familiar with any part of our code that could be producing that output.

**Comment by neozhang307** [comment]
I attached the log of running gdb in minimal-cuda-solver

[minimal-cuda-solver.log](https://github.com/ginkgo-project/ginkgo/files/6462857/minimal-cuda-solver.log)

I would submit a new issue if the 'No protocol specified' becomes a problem. 

Thank you

**Comment by upsj** [comment]
```
0x00000000004df89e in gko::Array<double>::resize_and_reset (this=0x13f69a08, 
    num_elems=2305843009213693952)
```
This seems to be the problem: For some reason, num_elems becomes huge, so we fulfill `size > 0`, but when computing the actual number of bytes for this number of double values, we overflow and try to allocate 0 bytes. And this behavior is reproducible? Would it be possible to share the matrix you are using?

**Comment by neozhang307** [comment]
The data is in /examples/minimal-cuda-solver/data default provided by Ginkgo. 

The behaviour is that:
I could get expected behaviour at A100. But running code at both P100 and V100 throws this AllocationError. 
And this problem solved by excitedly setting the aimed platform: "Pascal;Volta;Ampere"

My guess is that if set -DGINKGO_CUDA_ARCHITECTURES=Auto, it might not choose the platform in the current machine. My guess is that I might initially cmake in a machine with A100. After I build the code, the GPU kernel is by default generated only for A100. And thus I could not run code on machines with older GPUs. And I think the bug might not be the size of matrixs, it should be that the kernel can not run in older GPUs.

**Comment by upsj** [comment]
Thanks, that does indeed sound plausible. I'm just confused why none of the CUDA functions happening after the kernel launch returned an error, but I guess that is not too important right now.
So yeah, mismatching configurations between login and compute nodes are always annoying and not well-suited for architecture selection, we have similar issues on our local system, where the login nodes don't have GPUs. If I understand correctly, your issues should now be solved? If that is not true, feel free to reopen the issue :)
