### ISSUE TITLE
Make executor mismatch computations explicitly visible

### ISSUE THREAD

**Issue by pratikvn** [ginkgo-project/ginkgo#804]
Due to our first focus on functionality rather than performance, which is facilitated through the usage of `temporary_clone` functionality, we can transparently make executor copies, which is not ideal for performance. While these can be "debugged" through loggers, it might be useful for users to prevent these copies for the sake of performance and re-write their code. 

To resolve this, we should decide which transparent copies are allowable (host<-> host) and which are not (device<->host and host<->device), set a parent executing executor, and then throw in `temporary_clone`, if we are indeed copying to and from the non-allowed paths.

**Comment by tcojean** [comment]
Maybe we should at least have a specific logger event for these allocations, such as `temporary_copy` or something like that. There might be other places where these issues could arise, like when using Array. In general, modern C++ makes it very easy to write working but poorly performing code. It would be great to have knobs to easily debug these issues.

**Comment by upsj** [comment]
Yes, I like that idea. Something like a `PerformanceHintLogger` might help, computing what fraction of the runtime is taken by different operations, matching specific patterns of operations like repeated cross-executor copies.
