### ISSUE TITLE
Is axpy function needed?

### ISSUE THREAD

**Issue by yhmtsai** [ginkgo-project/ginkgo#82]
COO spmv kernels need to works on the output vector `c` first.
COO cuda kernels only do `c = A*b + c`
Thus, in spmv (`c = A*b = A*b + 0`), we set zero in `c` for ensuring kernel works correctly

In Hybrid format, its spmv function is composed of ELL and COO spmv functions.
```
ell_mtx->apply(b, x); // x = (ELL) * b
coo_mtx->apply(1, b, 1, x); // x = 1 * x + 1 * (COO) * b
```
The second command spends time to multiply `x` with 1, which is redundant.

Does It have any performance issue?
If it does, maybe we need the axpy function like `c = A*b + c` instead of calling advanced spmv.
```
ell_mtx->apply(b, x); // x = (ELL) * b
coo_mtx->axpy(b, x); // x = x + (COO) * b
```

**Comment by hartwiganzt** [comment]
To clearify:  this is only a performance issue: the COO kernel sets the output vector to zero first, in the hybrid kernel we don't need/want that. Is it reasonable to have a separate kernel for that?

**Comment by yhmtsai** [comment]
I have tested some matrices from Florida matrices to compare two hybrid spmv.
The Hybrid matrix strategy is automatically (imbalance with 0.8)
Hybrid spmv with Coo advanced spmv: It is the same flow as this repo now.
Hybrid spmv with Coo axpy: the flow is similar, but it calls the coo kernel without multiplying the output vector by 1.
The multiplying operation has the large effect on the performance when the nnz is small (< 1e6).

![performance-hybridwithdifferentcoo](https://user-images.githubusercontent.com/19565938/42683043-82cacfb8-868c-11e8-94b6-5cbcfc3d49b7.png)

![ratio-hybridwithdifferentcoo](https://user-images.githubusercontent.com/19565938/42683141-bbbb39fc-868c-11e8-9d33-35efe9e22279.png)

**Comment by tcojean** [comment]
Thanks for looking into it. Looks like we should indeed go with axpy.

**Comment by yhmtsai** [comment]
I also implement another Hybrid implementation.
It sets zero to the output vector and then applies Ell and Coo kernels simultaneously.
Ell and Coo kernels use atomic_add to add resulting value to the output vector.
Compare it with Hybrid with Coo apply2 function.

![performance-hybridwithatomicadd](https://user-images.githubusercontent.com/19565938/42825467-5ecf29b6-89e2-11e8-9146-c040526df410.png)

**Comment by tcojean** [comment]
This can be closed, I think. As the problem with this issue is solved.
