### ISSUE TITLE
Scalar Jacobi specialization incomplete

### ISSUE THREAD

**Issue by upsj** [ginkgo-project/ginkgo#838]
With the Scalar Jacobi specialization, there are a few places that need to be adapted as well:
* `write` uses block_ptrs, which are empty in scalar Jacobi, so we probably need to special-case this and ignore precision reduction
* `(conj_)transpose` needs to directly copy over the block values instead of calling the transpose_jacobi kernel
* `convert_to(Dense)` has the same issues as `write`.

**Comment by pratikvn** [comment]
Good catch! Let me know if you are working on this, otherwise I will create a PR. We could also add it to @yhmtsai 's existing PR.

**Comment by upsj** [comment]
Feel free to take over :) I didn't do much for it yet.
