### ISSUE TITLE
deal.II configuration with ginkgo

### ISSUE THREAD

**Issue by gfcas** [ginkgo-project/ginkgo#867]
First congratulations to the 1.4.0 release!

With the help of @pratikvn I have recently tried to build dealii with the ginkgo interface. However, it turned out that for a working interface we had to require the develop branch, which is now ginkgo-v1.4.0. In order to enforce v1.4.0 during the configuration of dealii I have written a query in the dealii cmake style, see https://github.com/gfcas/dealii/commit/9c4f1d711310d42bab5e9c579826109e4f3453d5

If you are fine with that, I would create a PR to dealii/dealii for this patch.

Maybe if you are interested, I have also added the ginkgo project to the dealii/candi (source-based toolchain installer) in https://github.com/dealii/candi/pull/194, with which it becomes very easy to configure and install dealii+ginkgo and many other libraries.

**Comment by upsj** [comment]
Is there a downside to using `find_package(Ginkgo 1.4.0)` instead of checking the version manually?

**Comment by gfcas** [comment]
Using ``find_package`` with the required version number works as well. I also tried this based on @pratikvn's comment. The manual check, however, is more flexible and it seems to be common pratice in dealii. In partucular, additional checks for external dependencies can be easily included, see for example the p4est configuration (https://github.com/dealii/dealii/blob/master/cmake/configure/configure_p4est.cmake).

**Comment by pratikvn** [comment]
I think here it is more of a choice and preference from the library side. deal.ii has to deal with libraries that have cmake support and some that dont. So for uniformity they might prefer to use version checking manually.

I would also prefer a `find_package(Ginkgo 1.4.0)`, as that is pretty clear and does not add too much additional code. 

But as this would be a modification in deal.ii, it would be better to get their opinions on that. I think you can maybe create a PR for your version and propose them both the versions to ask which they prefer.

**Comment by gfcas** [comment]
Thanks for your opinions! Let's see what the dealii community says (https://github.com/dealii/dealii/pull/12703).

**Comment by gfcas** [comment]
The suggested version check was merged in deal.II, so we can close this issue.
