### ISSUE TITLE
Build ginkgo - OMP failed to build

### ISSUE THREAD

**Issue by davidchaozhang** [ginkgo-project/ginkgo#955]
> Build ginkgo using CMAKE 3.22.1 in Windows10 calling MSVC 2019 as compiler:

Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17134.
Could NOT find OpenMP_C: Found unsuitable version "2.0", but required is at least "3.0" (found -openmp)
Could NOT find OpenMP_CXX: Found unsuitable version "2.0", but required is at least "3.0" (found -openmp)
Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) (Required is at least version "3.0")
GINKGO_BUILD_TESTS is ON, enabling GINKGO_BUILD_REFERENCE
Could NOT find PAPI (missing: PAPI_LIBRARY PAPI_INCLUDE_DIR) 
HWLOC is being forcibly switched off
Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) (Required is at least version "1.10.0")
Fetching external GTest

> It complains the omp version is old. Not sure where to download and how to solve this problem.

**Comment by upsj** [comment]
Unfortunately, that is not something we can influence - the OpenMP support in MSVC has been outdated for a long time now, even though there is some work in making it towards OpenMP 3.0, the only solution I see is to use another compiler, e.g. maybe try `clang-cl` or compile via MinGW? Though I cannot vouch for the performance that may give.

**Comment by davidchaozhang** [comment]
Thanks for the prompt reply. I found it hard to use MSVC to build the code. I am going to try to build in Linux.
